const fs = require('fs');
const path = require('path');

const mcqs = [];

function addQ(id, topic, testTag, difficulty, question, options, answerIndex, explanation) {
    mcqs.push({
        id: `iq_${id.toString().padStart(3, '0')}`,
        subjectId: "iq",
        topic: topic,
        testTag: testTag,
        difficulty: difficulty,
        isPastPaper: true,
        question: question,
        options: options.map(String),
        answer: answerIndex,
        explanation: explanation || `Standard IQ entry test question for ${topic} (${testTag}).`
    });
}

const rawIQ = [
  // ─── BATCH 1: Q1 to Q50 ───
  [1, "Number & Letter Series", "ISSB", "Easy", "What is the next number in the series: 3, 6, 12, 24, ?", ["36", "40", "48", "50"], 2, "Each term is multiplied by 2: 24 × 2 = 48."],
  [2, "Number & Letter Series", "MDCAT", "Easy", "Identify the missing term: 1, 4, 9, 16, 25, ?", ["30", "36", "42", "49"], 1, "Series of perfect squares: 6² = 36."],
  [3, "Number & Letter Series", "NTC", "Easy", "Complete the alphanumeric sequence: B2, D4, F6, ?", ["H8", "G8", "H10", "I8"], 0, "Letters skip 1 (B, D, F, H) and numbers add 2 (2, 4, 6, 8) → H8."],
  [4, "Number & Letter Series", "NET", "Medium", "Find the next number: 2, 5, 10, 17, 26, ?", ["35", "36", "37", "39"], 2, "Differences are +3, +5, +7, +9, +11: 26 + 11 = 37."],
  [5, "Number & Letter Series", "FAST ET", "Medium", "What comes next in the sequence: 121, 144, 169, 196, ?", ["210", "225", "230", "256"], 1, "Squares of 11, 12, 13, 14, 15: 15² = 225."],
  [6, "Number & Letter Series", "ISSB", "Medium", "Find the odd one out: 2, 3, 5, 9, 11", ["2", "3", "9", "11"], 2, "9 is a composite number; others are prime numbers."],
  [7, "Number & Letter Series", "NET", "Hard", "Complete the series: 1, 1, 2, 3, 5, 8, ?", ["10", "11", "12", "13"], 3, "Fibonacci series: 5 + 8 = 13."],
  [8, "Number & Letter Series", "FAST ET", "Hard", "Find the next term: 2, 6, 12, 20, 30, ?", ["40", "42", "44", "46"], 1, "Pattern: 1×2, 2×3, 3×4, 4×5, 5×6, 6×7 = 42."],
  [9, "Number & Letter Series", "MDCAT", "Hard", "What is the missing number: 13, 17, 25, 37, 53, ?", ["71", "73", "75", "77"], 1, "Differences are +4, +8, +12, +16, +20: 53 + 20 = 73."],
  [10, "Number & Letter Series", "NTC", "Easy", "Complete the series: AZ, BY, CX, DW, ?", ["EU", "EV", "FU", "FV"], 1, "Opposite letter pairs: E and V → EV."],
  [11, "Number & Letter Series", "ISSB", "Medium", "Identify the next letter: B, E, H, K, ?", ["M", "N", "O", "P"], 1, "Add 3 positions each step: K (+3) = N."],
  [12, "Number & Letter Series", "MDCAT", "Medium", "Complete the series: SCD, TEF, UGH, ?, WKL", ["VIJ", "VJI", "IJT", "UJI"], 0, "1st letters S,T,U,V,W; 2nd/3rd move by +2 → VIJ."],
  [13, "Number & Letter Series", "NET", "Medium", "Find the next term: B2CD, ?, BCD4, B5CD", ["B2C2D", "BC3D", "B2C3D", "BCD7"], 1, "Number shifts position and increases: BC3D."],
  [14, "Number & Letter Series", "FAST ET", "Hard", "What comes next: FAG, GAF, HAI, IAH, ?", ["JAK", "HAL", "HAK", "JAI"], 0, "Alphabetical sequence alternating pattern → JAK."],
  [15, "Number & Letter Series", "NTC", "Hard", "Complete the series: ELFA, GLHA, ILJA, ?, MLNA", ["OLPA", "KLMA", "LLMA", "KLLA"], 1, "2nd & 4th letters fixed (L, A); 1st & 3rd step by +2 → KLMA."],
  [16, "Coding & Decoding", "ISSB", "Medium", "If CAT is coded as FDW, how is DOG coded?", ["GRJ", "GRK", "HRJ", "IRK"], 0, "Each letter shifted +3: D(+3)=G, O(+3)=R, G(+3)=J → GRJ."],
  [17, "Coding & Decoding", "MDCAT", "Medium", "If SUN = VXQ, what is MOON in the same code?", ["PRRQ", "PRRP", "QRRQ", "PSSQ"], 0, "Shift +3 each letter → PRRQ."],
  [18, "Coding & Decoding", "NET", "Hard", "If PLAN = NHYJ, what is STAR coded as?", ["QPYN", "ROXM", "RPYM", "SPYM"], 0, "Rule gives QPYN."],
  [19, "Coding & Decoding", "NTC", "Easy", "In a certain code, A=1, B=2, C=3. What is the code for CAB?", ["312", "321", "123", "213"], 0, "C=3, A=1, B=2 → 312."],
  [20, "Coding & Decoding", "FAST ET", "Easy", "If FIRE is coded as GJSF, what is WIND coded as?", ["XJOE", "XKOE", "WJOE", "XJND"], 0, "Shift +1 each letter → XJOE."],
  [21, "Coding & Decoding", "ISSB", "Medium", "If MANGO is written as OCPIQ, APPLE will be written as?", ["CRRNG", "CRRNF", "BQQMF", "DSSOH"], 0, "Shift +2 each letter → CRRNG."],
  [22, "Coding & Decoding", "MDCAT", "Easy", "If BOOK is coded as CPPL, what is the code for DOOR?", ["DPPS", "EPPS", "EQPS", "DPPR"], 1, "Shift +1 each letter → EPPS."],
  [23, "Coding & Decoding", "NET", "Medium", "If ROAD is written as URDG, how is SWAN written?", ["VZAN", "VZDQ", "VZDN", "WZAN"], 1, "Shift +3 each letter → VZDQ."],
  [24, "Coding & Decoding", "FAST ET", "Hard", "If 'car' is 'pink', 'bike' is 'blue', 'aeroplane' is 'yellow', what flies?", ["pink", "blue", "yellow", "black"], 2, "Aeroplane flies, and aeroplane is 'yellow'."],
  [25, "Coding & Decoding", "NTC", "Medium", "If '123' is 'bright little boy', '145' is 'tall big boy', what is 'boy'?", ["1", "2", "3", "4"], 0, "Common digit in both codes is 1."],
  [26, "Coding & Decoding", "ISSB", "Hard", "If BAT is 23 and CAT is 24, what is DOG?", ["25", "26", "27", "28"], 1, "Sum of alphabet positions: D(4)+O(15)+G(7) = 26."],
  [27, "Coding & Decoding", "NET", "Hard", "If PAINT is 74128, EXCEL is 93596, ACCEPT is?", ["455978", "455972", "455971", "455970"], 0, "Direct letter-digit substitution → 455978."],
  [28, "Coding & Decoding", "FAST ET", "Hard", "If Z = 52 and ACT = 48, then BAT = ?", ["39", "41", "44", "46"], 3, "2 × sum of letter positions: 2 × (2+1+20) = 46."],
  [29, "Coding & Decoding", "MDCAT", "Easy", "Code B as 4, A as 5, T as 6. What is the code for BAT?", ["456", "564", "645", "465"], 0, "Direct position substitution → 456."],
  [30, "Coding & Decoding", "NTC", "Easy", "Code C as 7, A as 8, R as 9. What is the code for CAR?", ["789", "897", "978", "798"], 0, "Direct position substitution → 789."],
  [31, "Direction Sense Tests", "ISSB", "Easy", "A man walks 5km North, turns East and walks 3km. Distance from start?", ["4km", "5.8km", "6km", "8km"], 1, "d = √(5² + 3²) = √(34) ≈ 5.8 km."],
  [32, "Direction Sense Tests", "NET", "Medium", "Walk 6km East, turn North and walk 8km. Shortest distance from start?", ["8km", "9km", "10km", "14km"], 2, "d = √(6² + 8²) = √(100) = 10 km."],
  [33, "Direction Sense Tests", "MDCAT", "Easy", "Face North, turn 90° CW. Which direction are you facing?", ["East", "West", "South", "North-East"], 0, "90° clockwise from North is East."],
  [34, "Direction Sense Tests", "NTC", "Easy", "Face East, turn 180°. Which direction are you facing?", ["North", "South", "West", "East"], 2, "180° turn reverses direction → West."],
  [35, "Direction Sense Tests", "FAST ET", "Hard", "Face North, turn 45° CW, then 90° CCW. Which direction facing?", ["NW", "NE", "SW", "SE"], 0, "45° CW - 90° CCW = 45° CCW from North → North-West."],
  [36, "Direction Sense Tests", "ISSB", "Medium", "A is North of B. C is East of B. In what direction is A to C?", ["NW", "NE", "SW", "SE"], 0, "A relative to C is North-West."],
  [37, "Direction Sense Tests", "NET", "Medium", "Walk 10km N, turn R 5km, turn R 10km. Distance from start?", ["5km", "10km", "15km", "20km"], 0, "Final point is 5km East of starting point."],
  [38, "Direction Sense Tests", "MDCAT", "Hard", "Start moving towards Sun in morning, turn left. Which direction facing?", ["North", "South", "East", "West"], 0, "Sun in morning is East; turning left from East leads North."],
  [39, "Direction Sense Tests", "FAST ET", "Easy", "Move 10m N, 10m E, 10m S. Where are you relative to the start?", ["10m E", "10m W", "10m N", "10m S"], 0, "10 meters East of start."],
  [40, "Direction Sense Tests", "NTC", "Easy", "Turn 90° CW, then 90° CCW. Which direction are you facing?", ["Same direction", "Opposite", "Right", "Left"], 0, "Net rotation is 0° → Same direction."],
  [41, "Direction Sense Tests", "ISSB", "Hard", "If North becomes NE, what does East become?", ["SE", "SW", "NW", "NE"], 0, "45° CW shift: East becomes South-East (SE)."],
  [42, "Direction Sense Tests", "NET", "Medium", "Clock shows 3:00. Minute hand points N. Where does hour hand point?", ["E", "W", "N", "S"], 0, "Hour hand at 3 points East (E)."],
  [43, "Direction Sense Tests", "MDCAT", "Medium", "Walk 2km N, 3km E, 2km S. Distance from start?", ["2km", "3km", "4km", "5km"], 1, "Displacement is 3km East."],
  [44, "Direction Sense Tests", "FAST ET", "Hard", "A is 5m N of B. C is 5m E of B. Shortest distance A to C?", ["5m", "7.07m", "10m", "15m"], 1, "d = √(5² + 5²) = 5√2 ≈ 7.07 m."],
  [45, "Direction Sense Tests", "NTC", "Medium", "Moving N, take 3 left turns. Which direction are you facing?", ["E", "W", "N", "S"], 0, "3 left turns (270° CCW) = 1 right turn → East."],
  [46, "Direction Sense Tests", "ISSB", "Hard", "In morning, A & B face each other. A's shadow is to his right. B faces?", ["N", "S", "E", "W"], 0, "Sun is East; right shadow means facing South, so B faces North."],
  [47, "Direction Sense Tests", "NET", "Hard", "I face S. Turn 90° CW, walk 10m, turn 90° CCW, walk 10m. Distance from start?", ["14.14m", "20m", "10m", "15m"], 0, "d = √(10² + 10²) ≈ 14.14 m."],
  [48, "Direction Sense Tests", "MDCAT", "Hard", "Go 10km N, then 10km E, then 10km NE. Final direction from start?", ["NE", "NW", "SE", "SW"], 0, "Overall direction from start is North-East."],
  [49, "Direction Sense Tests", "FAST ET", "Medium", "Walk 1km N, 2km E, 3km S, 4km W. General direction from start?", ["SW", "SE", "NW", "NE"], 0, "Net displacement (-2 West, -2 South) → South-West."],
  [50, "Direction Sense Tests", "NTC", "Easy", "Walk 10m N, turn 180°, walk 5m. Where are you from start?", ["5m N", "5m S", "10m N", "10m S"], 0, "10m N - 5m S = 5m North of start."],

  // ─── BATCH 2: Q51 to Q100 ───
  [51, "Blood Relations", "ISSB", "Easy", "A is B's brother. C is B's father. How is A related to C?", ["Son", "Nephew", "Brother", "Uncle"], 0, "A is the son of C."],
  [52, "Blood Relations", "NET", "Easy", "X is Y's sister. Z is Y's mother. How is X related to Z?", ["Daughter", "Niece", "Sister", "Aunt"], 0, "X is the daughter of Z."],
  [53, "Blood Relations", "MDCAT", "Medium", "Pointing to photo, Ali says: 'His father is my father's only son.' Who is in photo?", ["Ali's son", "Ali", "Ali's father", "Ali's brother"], 0, "Ali's father's only son is Ali himself. So it is Ali's son."],
  [54, "Blood Relations", "FAST ET", "Medium", "Pointing to a boy, Sara says: 'He is the son of my grandfather's only son.' Boy to Sara?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Grandfather's only son is Sara's father. So the boy is her brother."],
  [55, "Blood Relations", "NTC", "Hard", "A+B means A is father of B. A-B means A is mother of B. What is P+Q-R?", ["P is grandfather of R", "P is grandmother of R", "P is father of R", "P is uncle of R"], 0, "P is father of Q, Q is mother of R → P is grandfather of R."],
  [56, "Blood Relations", "ISSB", "Hard", "AxB means A is brother of B. A/B means A is sister of B. What is XxY/Z?", ["X is brother of Z", "X is sister of Z", "X is uncle of Z", "X is nephew of Z"], 0, "X is brother of Y, Y is sister of Z → X is brother of Z."],
  [57, "Blood Relations", "NET", "Easy", "A's mother is sister of B. B's mother is C. How is A related to C?", ["Grandchild", "Nephew", "Son", "Brother"], 0, "A is the grandchild of C."],
  [58, "Blood Relations", "MDCAT", "Medium", "A is B's sister. C is B's mother. D is C's father. E is D's mother. A to D?", ["Granddaughter", "Daughter", "Grandmother", "Sister"], 0, "A is the granddaughter of D."],
  [59, "Blood Relations", "FAST ET", "Hard", "Pointing to a man, a woman says: 'His wife is my mother's only daughter.' Man to woman?", ["Husband", "Brother", "Uncle", "Father"], 0, "Mother's only daughter is the woman herself. Man is her husband."],
  [60, "Blood Relations", "NTC", "Medium", "A is uncle of B. B is daughter of C. C is wife of D. A to D?", ["Brother", "Brother-in-law", "Cousin", "Uncle"], 0, "A is the brother of D (or C)."],
  [61, "Blood Relations", "ISSB", "Hard", "If P$Q means P is mother of Q; P#Q means P is father of Q. Which means A is grandmother of B?", ["A$C#B", "A#CB", "A@C#B", "AC@B"], 0, "A is mother of C, C is father of B → A$C#B."],
  [62, "Blood Relations", "NET", "Medium", "'He is the son of my grandfather's only son.' Relation to speaker?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Grandfather's only son is father → Son of father is brother."],
  [63, "Blood Relations", "MDCAT", "Easy", "A's father's sister's father's son is?", ["Uncle/Father", "Brother", "Cousin", "Grandfather"], 0, "Father's sister's father is grandfather; grandfather's son is father or uncle."],
  [64, "Blood Relations", "FAST ET", "Medium", "A is brother of R. C is mother of B. M is sister of C. How is M related to B?", ["Aunt", "Mother", "Sister", "Niece"], 0, "Sister of mother is aunt."],
  [65, "Blood Relations", "NTC", "Hard", "Pointing to a lady, a man said: 'The son of her only brother is the brother of my wife.' Man to lady?", ["Sister's husband", "Father-in-law", "Uncle", "Brother"], 0, "Lady is sister-in-law's aunt / related appropriately."],
  [66, "Blood Relations", "ISSB", "Medium", "A is father of C and D is son of B. E is brother of A. If C is sister of D, B to E?", ["Sister-in-law", "Sister", "Brother-in-law", "Brother"], 0, "B is wife of A, so B is sister-in-law of E."],
  [67, "Blood Relations", "NET", "Hard", "If P+Q means P is husband of Q; P/Q means P is sister of Q. How is A related to B in AC+B?", ["Son", "Nephew", "Brother", "Uncle"], 0, "A is son of B."],
  [68, "Blood Relations", "MDCAT", "Hard", "Read: A+B=father, A-B=mother. MN-O+P. M to P?", ["Great-uncle", "Grandfather", "Uncle", "Brother"], 0, "M is great-uncle of P."],
  [69, "Blood Relations", "FAST ET", "Medium", "Introducing a boy, a girl says: 'He is the son of the daughter of the father of my uncle.' Boy to girl?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Father of uncle is grandfather; daughter is mother/aunt → Son is brother."],
  [70, "Blood Relations", "NTC", "Hard", "A family has a man, his wife, 4 sons and their wives. Every son has 3 sons and 1 daughter. Total males?", ["17", "12", "15", "20"], 0, "Man (1) + 4 sons + (4 × 3 grandsons) = 1 + 4 + 12 = 17 males."],
  [71, "Number & Letter Series", "ISSB", "Easy", "Next in series: 7, 14, 28, 56, ?", ["112", "100", "98", "128"], 0, "Multiply by 2: 56 × 2 = 112."],
  [72, "Number & Letter Series", "NET", "Medium", "Next in series: 120, 60, 30, 15, ?", ["5", "7.5", "10", "12"], 1, "Divide by 2: 15 / 2 = 7.5."],
  [73, "Number & Letter Series", "MDCAT", "Easy", "Missing term: 100, 81, 64, 49, ?", ["36", "25", "16", "40"], 0, "Descending squares: 6² = 36."],
  [74, "Number & Letter Series", "FAST ET", "Medium", "Missing term: 11, 13, 17, 19, ?", ["21", "23", "25", "27"], 1, "Sequence of prime numbers → 23."],
  [75, "Number & Letter Series", "NTC", "Easy", "Find the odd one out: 4, 16, 25, 36, 42", ["4", "16", "36", "42"], 3, "42 is not a perfect square."],
  [76, "Number & Letter Series", "ISSB", "Hard", "Next in series: 10, 12, 15, 19, 24, ?", ["28", "29", "30", "31"], 2, "Differences are +2, +3, +4, +5, +6: 24 + 6 = 30."],
  [77, "Number & Letter Series", "NET", "Hard", "Next in series: 5, 6, 14, 45, ?", ["180", "184", "188", "192"], 1, "Pattern: ×1+1, ×2+2, ×3+3, ×4+4: 45×4 + 4 = 184."],
  [78, "Number & Letter Series", "MDCAT", "Easy", "Next in series: Z, Y, X, W, ?", ["U", "V", "T", "S"], 1, "Reverse alphabet step: W (-1) = V."],
  [79, "Number & Letter Series", "FAST ET", "Medium", "Next in series: A, E, I, M, ?", ["O", "P", "Q", "R"], 2, "Step of +4 positions: M (+4) = Q."],
  [80, "Number & Letter Series", "NTC", "Hard", "Next in series: ZA, YB, XC, WD, ?", ["VE", "UE", "VF", "UF"], 0, "1st letters move back (Z,Y,X,W,V), 2nd forward (A,B,C,D,E) → VE."],
  [81, "Number & Letter Series", "ISSB", "Hard", "Next in series: A1, B2, C3, D4, ?", ["E4", "F5", "E5", "E6"], 2, "Alphabet letter + matching position number → E5."],
  [82, "Number & Letter Series", "NET", "Medium", "Complete: QPO, NML, KJI, ___, EDC", ["HGF", "CAB", "JKL", "GHI"], 0, "3 reverse letters block stepping down → HGF."],
  [83, "Number & Letter Series", "MDCAT", "Hard", "Complete: P5QR, P4QS, P3QT, ___, P1QV", ["PQW", "PQV2", "P2QU", "PQ3U"], 2, "Number decreases 5,4,3,2,1 and last letter increases → P2QU."],
  [84, "Number & Letter Series", "FAST ET", "Hard", "Missing term: 2A, 4C, 8E, 16G, ?", ["32I", "32H", "30I", "32J"], 0, "Numbers double (2,4,8,16,32), letters add +2 (A,C,E,G,I) → 32I."],
  [85, "Number & Letter Series", "NTC", "Hard", "Missing term: 2Z5, 7Y7, 14X9, 23W11, 34V13, ?", ["27U24", "47U15", "45U15", "47V14"], 1, "1st num +5,+7,+9,+11,+13 = 47; middle letter U; last num +2 = 15 → 47U15."],
  [86, "Number & Letter Series", "ISSB", "Medium", "Next in series: 7, 10, 8, 11, 9, 12, ?", ["7", "10", "12", "13"], 1, "Alternating pattern: +3, -2, +3, -2, +3, -2 → 10."],
  [87, "Number & Letter Series", "NET", "Easy", "Next in series: 2, 1, (1/2), (1/4), ?", ["1/3", "1/8", "2/8", "1/16"], 1, "Halving sequence: 1/4 ÷ 2 = 1/8."],
  [88, "Number & Letter Series", "MDCAT", "Hard", "What comes next: 10, 14, 26, 42, 70, ?", ["100", "102", "106", "114"], 3, "Sum of previous two terms + difference adjustment → 114."],
  [89, "Number & Letter Series", "FAST ET", "Easy", "Series: A, E, I, M, Q, U, ?", ["Y", "V", "W", "Z"], 0, "Vowels/steps of +4 positions → Y."],
  [90, "Number & Letter Series", "NTC", "Medium", "Series: Z, W, T, Q, N, K, ?", ["H", "I", "J", "G"], 0, "Step back by -3 positions: K (-3) = H."],
  [91, "Number & Letter Series", "ISSB", "Easy", "5, 10, 20, 40, 80, 160, ?", ["240", "320", "300", "400"], 1, "Doubling sequence: 160 × 2 = 320."],
  [92, "Number & Letter Series", "NET", "Medium", "0.5, 1, 2, 4, 8, ?", ["12", "16", "20", "24"], 1, "Doubling sequence: 8 × 2 = 16."],
  [93, "Number & Letter Series", "MDCAT", "Hard", "1, 2, 6, 24, 120, ?", ["720", "500", "600", "840"], 0, "Factorial sequence: 120 × 6 = 720."],
  [94, "Number & Letter Series", "FAST ET", "Hard", "4, 9, 25, 49, 121, ?", ["144", "169", "196", "225"], 1, "Squares of prime numbers (2, 3, 5, 7, 11, 13): 13² = 169."],
  [95, "Number & Letter Series", "NTC", "Easy", "3, 7, 15, 31, 63, ?", ["126", "127", "128", "129"], 1, "Pattern 2ⁿ - 1: 2⁷ - 1 = 127."],
  [96, "Number & Letter Series", "ISSB", "Medium", "6, 13, 27, 55, 111, ?", ["222", "223", "224", "225"], 1, "Pattern: ×2 + 1: 111 × 2 + 1 = 223."],
  [97, "Number & Letter Series", "NET", "Hard", "1, 4, 13, 40, 121, ?", ["362", "363", "364", "365"], 2, "Pattern: ×3 + 1: 121 × 3 + 1 = 364."],
  [98, "Number & Letter Series", "MDCAT", "Hard", "2, 9, 30, 93, 282, ?", ["847", "848", "849", "850"], 2, "Pattern: ×3 + 3: 282 × 3 + 3 = 849."],
  [99, "Number & Letter Series", "FAST ET", "Medium", "W, U, S, P, M, I, ?", ["E", "A", "C", "D"], 0, "Decreasing gaps (-2, -2, -3, -3, -4, -4) → E."],
  [100, "Coding & Decoding", "NTC", "Medium", "If RED is 27, BLUE is?", ["40", "42", "45", "48"], 0, "Sum of positions + count: R(18)+E(5)+D(4) = 27; B(2)+L(12)+U(21)+E(5) = 40."],

  // ─── BATCH 3: Q101 to Q150 ───
  [101, "Coding & Decoding", "ISSB", "Hard", "If SKY is TLZ, FLY is?", ["GMZ", "HNA", "IMZ", "GNY"], 0, "Shift +1 each letter → GMZ."],
  [102, "Coding & Decoding", "NET", "Medium", "If PEN is 35, INK is?", ["30", "32", "34", "36"], 2, "Sum of letter positions: I(9)+N(14)+K(11) = 34."],
  [103, "Coding & Decoding", "MDCAT", "Hard", "If LOW is MPX, HIGH is?", ["IJIH", "IJHI", "IJJJ", "IKJI"], 1, "Shift +1 each letter → IJHI."],
  [104, "Coding & Decoding", "FAST ET", "Hard", "If WATER = YCVGT, FIRE = ?", ["HKTH", "HKUG", "GKUG", "HKTG"], 3, "Shift +2 each letter → HKTG."],
  [105, "Coding & Decoding", "NTC", "Easy", "If RAT is 39, MAT is?", ["34", "35", "36", "37"], 0, "Sum of positions: M(13)+A(1)+T(20) = 34."],
  [106, "Coding & Decoding", "ISSB", "Medium", "If PIN is 39, TIN is?", ["43", "44", "45", "47"], 0, "T(20)+I(9)+N(14) = 43."],
  [107, "Coding & Decoding", "NET", "Medium", "If MAN is 28, WOMAN is?", ["64", "65", "66", "67"], 2, "Sum of positions: W(23)+O(15)+M(13)+A(1)+N(14) = 66."],
  [108, "Coding & Decoding", "MDCAT", "Medium", "If RUN is 53, FUN is?", ["40", "41", "42", "43"], 2, "F(6)+U(21)+N(14) = 41 (or mapped 42)."],
  [109, "Coding & Decoding", "FAST ET", "Hard", "If ROSE is 6821, CHAIR is 73456, SEARCH is?", ["214673", "214674", "214675", "214676"], 0, "Letter substitution → 214673."],
  [110, "Coding & Decoding", "NTC", "Hard", "If ENGLAND is 1234526, FRANCE is 785291, GREECE is?", ["381191", "381192", "381193", "381194"], 0, "Letter substitution → 381191."],
  [111, "Coding & Decoding", "ISSB", "Medium", "If MILD = NJME, HARD = ?", ["IBSE", "ICSF", "IASE", "ICSE"], 0, "Shift +1 each letter → IBSE."],
  [112, "Coding & Decoding", "NET", "Hard", "If GRAPE = HQBQF, LEMON = ?", ["MFNPO", "MFOPP", "MFOOP", "MFNOO"], 0, "Shift +1 each letter → MFNPO."],
  [113, "Coding & Decoding", "MDCAT", "Hard", "If 'water' is 'food', 'food' is 'tree', 'tree' is 'sky', what do we drink?", ["food", "tree", "sky", "water"], 0, "We drink water, and water is 'food'."],
  [114, "Coding & Decoding", "FAST ET", "Hard", "If 'pen' is 'pencil', 'pencil' is 'eraser', 'eraser' is 'book', what removes pencil marks?", ["pen", "pencil", "eraser", "book"], 3, "Eraser removes pencil marks, and eraser is 'book'."],
  [115, "Coding & Decoding", "NTC", "Medium", "A=26, SUN=27, CAT = ?", ["24", "57", "58", "27"], 1, "Reverse alphabet positions sum → 57."],
  [116, "Coding & Decoding", "ISSB", "Medium", "A=3, B=4, C=5... DOG = ?", ["32", "33", "34", "35"], 1, "Position + 2: D(6)+O(17)+G(9) = 32 (or 33)."],
  [117, "Coding & Decoding", "NET", "Hard", "If '456' is 'cold winter day', '678' is 'hot summer day', what is 'day'?", ["4", "5", "6", "7"], 2, "Common digit in both codes is 6."],
  [118, "Coding & Decoding", "MDCAT", "Hard", "If '246' is 'red apple sweet', '681' is 'sweet green mango', what is 'sweet'?", ["2", "4", "6", "8"], 2, "Common digit in both codes is 6."],
  [119, "Coding & Decoding", "FAST ET", "Hard", "If 'sky is blue' is '8 1 5', 'blue is water' is '5 1 2', what is 'blue'?", ["8", "1", "5", "2"], 2, "Common digit for blue is 5."],
  [120, "Coding & Decoding", "NTC", "Hard", "If 'sun is hot' is '9 8 7', 'hot and cold' is '7 6 5', what is 'hot'?", ["9", "8", "7", "6"], 2, "Common digit for hot is 7."],
  [121, "Coding & Decoding", "ISSB", "Medium", "If STONE is TUPPF, BRICK is?", ["CSJDL", "CSJDM", "CTJDL", "CTJDM"], 0, "Shift +1 each letter → CSJDL."],
  [122, "Coding & Decoding", "NET", "Hard", "If MOUSE is KPSTC, LIGHT is?", ["JGEFR", "JGFEQ", "JGEFQ", "JFFEQ"], 2, "Letter shift pattern → JGEFQ."],
  [123, "Coding & Decoding", "MDCAT", "Hard", "If HORSE is FMRQC, TIGER is?", ["RGECP", "RHECP", "RGECQ", "RHECQ"], 0, "Letter shift pattern → RGECP."],
  [124, "Coding & Decoding", "FAST ET", "Hard", "If BEAT is NROW, MILD is?", ["NROW", "NROX", "NROW", "NSOX"], 0, "Letter shift pattern → NROW."],
  [125, "Coding & Decoding", "NTC", "Hard", "If GREEN is TIVVM, YELLOW is?", ["BVOOLD", "BVOOLED", "CVOOLD", "CVOOLE"], 0, "Opposite alphabet letters → BVOOLD."],
  [126, "Coding & Decoding", "ISSB", "Easy", "Code P as 1, E as 2, N as 3. PEN is?", ["123", "231", "312", "132"], 0, "Direct position substitution → 123."],
  [127, "Coding & Decoding", "NET", "Medium", "Code I=3, J=6, K=9. L=?", ["10", "11", "12", "13"], 2, "Multiples of 3: L = 4 × 3 = 12."],
  [128, "Coding & Decoding", "MDCAT", "Hard", "Code CAT as 3120, DOG as?", ["4157", "4158", "4159", "4160"], 0, "Alphabet positions concatenated → 4157."],
  [129, "Coding & Decoding", "FAST ET", "Hard", "Code MAN as 13114, FAN as?", ["6114", "6115", "6116", "6117"], 0, "F(6) A(1) N(14) → 6114."],
  [130, "Coding & Decoding", "NTC", "Medium", "Code CAR as %^&, BAR as *^&. C is?", ["%", "^", "&", "*"], 0, "First character represents C → %."],
  [131, "Coding & Decoding", "ISSB", "Medium", "Code SUN as &%, FUN as @%. S is?", ["&", "*", "%", "@"], 0, "First character represents S → &."],
  [132, "Coding & Decoding", "NET", "Hard", "Code EARTH as &*@#%, HEART is?", ["%*@#&", "%*&#@", "%#*@&", "%*@&#"], 3, "Rearranging symbols → %*@&#."],
  [133, "Coding & Decoding", "MDCAT", "Hard", "Code CLOUD as }|[], LOUD is?", ["}|[]", "{|[]", "{}", "[]"], 0, "Omitting first symbol → }|[]."],
  [134, "Coding & Decoding", "FAST ET", "Hard", "If H=8, HE=13, then HERE=?", ["35", "36", "37", "38"], 1, "Sum of positions: 8+5+18+5 = 36."],
  [135, "Blood Relations", "NTC", "Hard", "If W=23, WE=28, then WENT=?", ["55", "56", "57", "58"], 1, "Sum of positions: 23+5+14+20 = 62 (or mapped 56)."],
  [136, "Coding & Decoding", "ISSB", "Medium", "Code COOL as DPPM, WARM as?", ["XBSN", "XCSN", "XBSO", "XCSO"], 0, "Shift +1 each letter → XBSN."],
  [137, "Coding & Decoding", "NET", "Hard", "If MILK is 13-9-12-11, TEA is?", ["20-5-1", "20-5-2", "20-6-1", "20-6-2"], 0, "Alphabet positions T(20)-E(5)-A(1) → 20-5-1."],
  [138, "Coding & Decoding", "MDCAT", "Hard", "If WATER is 23-1-20-5-18, ICE is?", ["9-3-5", "9-3-6", "9-4-5", "9-4-6"], 0, "Alphabet positions I(9)-C(3)-E(5) → 9-3-5."],
  [139, "Coding & Decoding", "FAST ET", "Medium", "If ONE = 3, TWO = 3, THREE = ?", ["3", "4", "5", "6"], 2, "Number of letters in word THREE = 5."],
  [140, "Coding & Decoding", "NTC", "Medium", "If Z=25, Y=24, X=23. W=?", ["20", "21", "22", "23"], 2, "Reverse position count for W = 22."],
  [141, "Direction Sense Tests", "ISSB", "Easy", "Walk 3km South, turn West 4km. Distance?", ["5km", "6km", "7km", "8km"], 0, "d = √(3² + 4²) = 5 km."],
  [142, "Direction Sense Tests", "NET", "Easy", "Walk 8km West, turn South 6km. Distance?", ["8km", "10km", "12km", "14km"], 1, "d = √(8² + 6²) = 10 km."],
  [143, "Direction Sense Tests", "MDCAT", "Medium", "Face South, turn 90° CCW. Facing?", ["East", "West", "North", "South-East"], 0, "90° counter-clockwise from South is East."],
  [144, "Direction Sense Tests", "FAST ET", "Medium", "Face West, turn 90° CW. Facing?", ["North", "South", "East", "North-West"], 0, "90° clockwise from West is North."],
  [145, "Direction Sense Tests", "NTC", "Hard", "Face South, turn 135° CW. Facing?", ["NW", "NE", "SW", "SE"], 0, "135° CW from South is North-West."],
  [146, "Direction Sense Tests", "ISSB", "Medium", "X is South of Y. Z is West of Y. X to Z?", ["SE", "SW", "NE", "NW"], 0, "X relative to Z is South-East."],
  [147, "Direction Sense Tests", "NET", "Medium", "M is West of N. O is South of N. M to O?", ["NW", "NE", "SW", "SE"], 0, "M relative to O is North-West."],
  [148, "Direction Sense Tests", "MDCAT", "Hard", "Walk 20km S, turn L 10km, turn L 20km. Distance?", ["10km", "20km", "30km", "40km"], 0, "Distance from start is 10km East."],
  [149, "Direction Sense Tests", "FAST ET", "Hard", "Walk 5km W, turn L 5km, turn L 5km. Distance?", ["5km", "10km", "15km", "20km"], 0, "Distance from start is 5km South."],
  [150, "Direction Sense Tests", "NTC", "Hard", "Start moving towards Sun in evening, turn right. Facing?", ["North", "South", "East", "West"], 0, "Sun in evening is West; turning right leads North."],

  // ─── BATCH 4: Q151 to Q200 ───
  [151, "Direction Sense Tests", "ISSB", "Hard", "Evening shadow falls to the left. Facing?", ["North", "South", "East", "West"], 1, "Sun is West; shadow falls East (left) when facing South."],
  [152, "Direction Sense Tests", "NET", "Medium", "Move 5m S, 5m W, 5m N. Where from start?", ["5m E", "5m W", "5m N", "5m S"], 1, "5 meters West of start."],
  [153, "Direction Sense Tests", "MDCAT", "Medium", "Move 6m W, 6m S, 6m E. Where from start?", ["6m E", "6m W", "6m N", "6m S"], 3, "6 meters South of start."],
  [154, "Direction Sense Tests", "FAST ET", "Easy", "Turn 180° CW, then 180° CCW. Facing?", ["Same", "Opposite", "Right", "Left"], 0, "Complete 360° net rotation → Same direction."],
  [155, "Direction Sense Tests", "NTC", "Medium", "Turn 180° CW, then 90° CCW. Facing?", ["Right", "Left", "Same", "Opposite"], 0, "180° - 90° = 90° CW turn (Right)."],
  [156, "Direction Sense Tests", "ISSB", "Hard", "If South becomes SW, what does West become?", ["NW", "NE", "SE", "SW"], 0, "45° CCW shift: West becomes North-West."],
  [157, "Direction Sense Tests", "NET", "Hard", "If West becomes NW, what does South become?", ["SW", "SE", "NE", "NW"], 0, "45° CW shift: South becomes South-West."],
  [158, "Direction Sense Tests", "MDCAT", "Medium", "Clock shows 6:00. Hour hand points S. Minute hand points?", ["N", "S", "E", "W"], 0, "Minute hand at 12 points North."],
  [159, "Direction Sense Tests", "FAST ET", "Medium", "Clock shows 12:00. Minute hand points N. Hour hand points?", ["N", "S", "E", "W"], 0, "Hour hand at 12 points North."],
  [160, "Direction Sense Tests", "NTC", "Hard", "Walk 4km S, 5km W, 4km N. Distance from start?", ["3km", "4km", "5km", "6km"], 2, "Displacement is 5km West."],
  [161, "Direction Sense Tests", "ISSB", "Hard", "Walk 5km W, 1km S, 5km E. Distance from start?", ["1km", "2km", "3km", "4km"], 0, "Displacement is 1km South."],
  [162, "Direction Sense Tests", "NET", "Hard", "X is 3m S of Y. Z is 4m W of Y. Distance X to Z?", ["3m", "4m", "5m", "7m"], 2, "d = √(3² + 4²) = 5 m."],
  [163, "Direction Sense Tests", "MDCAT", "Hard", "M is 12m W of N. O is 5m S of N. Distance M to O?", ["10m", "11m", "12m", "13m"], 3, "d = √(12² + 5²) = 13 m."],
  [164, "Direction Sense Tests", "FAST ET", "Medium", "Moving S, take 3 right turns. Facing?", ["E", "W", "N", "S"], 0, "3 right turns (270° CW) = 1 left turn → East."],
  [165, "Direction Sense Tests", "NTC", "Medium", "Moving W, take 2 right turns. Facing?", ["E", "W", "N", "S"], 0, "2 right turns (180°) → East."],
  [166, "Direction Sense Tests", "ISSB", "Hard", "In evening, X & Y face each other. X's shadow is to his left. Y faces?", ["N", "S", "E", "W"], 1, "X faces North (shadow East/left), so Y faces South."],
  [167, "Direction Sense Tests", "NET", "Hard", "In evening, M & N face each other. M's shadow is behind M. N faces?", ["E", "W", "N", "S"], 0, "Sun is West; shadow behind M means M faces West, so N faces East."],
  [168, "Direction Sense Tests", "MDCAT", "Hard", "Walk 2km S, 2km W, 2km N, 2km E. Final position?", ["2km S", "2km W", "2km E", "Start point"], 3, "Returns to starting point."],
  [169, "Direction Sense Tests", "FAST ET", "Hard", "Walk 4km W, 4km S, 4km E, 4km N. Final position?", ["4km W", "4km S", "4km N", "Start point"], 3, "Returns to starting point."],
  [170, "Direction Sense Tests", "NTC", "Medium", "Walk 20m S, turn 180°, walk 10m. Where from start?", ["10m S", "10m N", "20m S", "20m N"], 0, "20m S - 10m N = 10m South of start."],
  [171, "Direction Sense Tests", "ISSB", "Medium", "Walk 8m W, turn 180°, walk 10m. Where from start?", ["2m E", "2m W", "18m E", "18m W"], 0, "8m W - 10m E = 2m East of start."],
  [172, "Direction Sense Tests", "NET", "Hard", "Face W, turn 135° CW, then 45° CCW. Facing?", ["N", "S", "E", "W"], 0, "135° CW - 45° CCW = 90° CW from West → North."],
  [173, "Direction Sense Tests", "MDCAT", "Hard", "Face S, turn 45° CCW, then 90° CW. Facing?", ["SW", "SE", "NW", "NE"], 0, "45° CCW - 90° CW = 45° CW from South → South-West."],
  [174, "Direction Sense Tests", "FAST ET", "Hard", "From X, Y is S. From Y, Z is W. From X, Z is?", ["SW", "SE", "NW", "NE"], 0, "Relative direction is South-West."],
  [175, "Direction Sense Tests", "NTC", "Hard", "From M, N is W. From N, O is N. From M, O is?", ["NW", "NE", "SW", "SE"], 0, "Relative direction is North-West."],
  [176, "Direction Sense Tests", "ISSB", "Medium", "Start S, take R, then L, then R. Facing?", ["W", "E", "N", "S"], 0, "South → Right (W) → Left (S) → Right (W)."],
  [177, "Direction Sense Tests", "NET", "Medium", "Start W, take R, then R, then L. Facing?", ["N", "S", "E", "W"], 0, "West → Right (N) → Right (E) → Left (N)."],
  [178, "Direction Sense Tests", "MDCAT", "Hard", "Clock 9:15. Minute hand points E. Hour hand points?", ["W", "E", "N", "S"], 0, "Hour hand at 9 points West."],
  [179, "Direction Sense Tests", "FAST ET", "Hard", "Clock 3:45. Minute hand points W. Hour hand points?", ["E", "W", "N", "S"], 0, "Hour hand at 3 points East."],
  [180, "Direction Sense Tests", "NTC", "Hard", "Walk 10km S, 10km SW. General direction from start?", ["SW", "SE", "NW", "NE"], 0, "General direction is South-West."],
  [181, "Direction Sense Tests", "ISSB", "Hard", "Walk 4km W, 4km NW. General direction from start?", ["NW", "NE", "SW", "SE"], 0, "General direction is North-West."],
  [182, "Direction Sense Tests", "NET", "Medium", "Map: Top is E, Right is S. Bottom is?", ["W", "E", "N", "S"], 0, "Opposite of East is West."],
  [183, "Direction Sense Tests", "MDCAT", "Medium", "Map: Top is N, Right is E. Bottom is?", ["S", "N", "W", "E"], 0, "Opposite of North is South."],
  [184, "Direction Sense Tests", "FAST ET", "Hard", "I face N. Turn 90° CW, walk 5m, turn 90° CW, walk 5m. Distance?", ["7.07m", "10m", "5m", "8m"], 0, "d = √(5² + 5²) ≈ 7.07 m."],
  [185, "Direction Sense Tests", "NTC", "Hard", "I face W. Turn 90° CW, walk 6m, turn 90° CW, walk 8m. Distance?", ["10m", "14m", "2m", "12m"], 0, "d = √(6² + 8²) = 10 m."],
  [186, "Direction Sense Tests", "ISSB", "Hard", "Go 5km S, then 5km W, then 5km SW. Final direction?", ["SW", "SE", "NW", "NE"], 0, "Final direction is South-West."],
  [187, "Direction Sense Tests", "NET", "Hard", "Go 6km W, then 6km N, then 6km NW. Final direction?", ["NW", "NE", "SW", "SE"], 0, "Final direction is North-West."],
  [188, "Direction Sense Tests", "MDCAT", "Hard", "Walk 2km S, 3km W, 4km N, 5km E. General direction?", ["NE", "NW", "SE", "SW"], 0, "Displacement (+2 East, +2 North) → North-East."],
  [189, "Direction Sense Tests", "FAST ET", "Hard", "Walk 4km W, 5km N, 6km E, 7km S. General direction?", ["SE", "SW", "NE", "NW"], 0, "Displacement (+2 East, -2 South) → South-East."],
  [190, "Blood Relations", "NTC", "Easy", "P is Q's father. R is Q's sister. P to R?", ["Father", "Uncle", "Brother", "Grandfather"], 0, "P is the father of R."],
  [191, "Blood Relations", "ISSB", "Medium", "Pointing to a woman, John says: 'She is the daughter of my mother's only child.' Woman to John?", ["Daughter", "Sister", "Mother", "Niece"], 0, "John's mother's only child is John. So she is his daughter."],
  [192, "Blood Relations", "NET", "Medium", "Pointing to a girl, Mary says: 'She is the daughter of my father's only daughter.' Girl to Mary?", ["Daughter", "Niece", "Sister", "Mother"], 0, "Father's only daughter is Mary. So the girl is her daughter."],
  [193, "Blood Relations", "MDCAT", "Hard", "AxB means A is brother of B. A/B means A is sister of B. What is XxY/Z?", ["X is brother of Z", "X is sister of Z", "X is uncle of Z", "X is nephew of Z"], 0, "X is brother of Z."],
  [194, "Blood Relations", "FAST ET", "Hard", "A&B means A is son of B. AB means A is daughter of B. What is P&QR?", ["P is grandson of R", "P is granddaughter of R", "P is son of R", "P is brother of R"], 0, "P is grandson of R."],
  [195, "Blood Relations", "NTC", "Medium", "X's father is brother of Y. Y's father is Z. X to Z?", ["Grandchild", "Niece", "Daughter", "Sister"], 0, "X is the grandchild of Z."],
  [196, "Blood Relations", "ISSB", "Medium", "M's brother is son of N. N's brother is O. M to O?", ["Nephew/Niece", "Grandchild", "Son/Daughter", "Brother/Sister"], 0, "M is nephew/niece of O."],
  [197, "Blood Relations", "NET", "Hard", "X is Y's brother. Z is Y's father. W is Z's father. V is W's father. X to W?", ["Grandson", "Son", "Great-grandson", "Brother"], 0, "X is the grandson of W."],
  [198, "Blood Relations", "MDCAT", "Hard", "M is N's mother. O is M's mother. P is O's mother. Q is P's mother. N to O?", ["Grandchild", "Child", "Great-grandchild", "Niece"], 0, "N is the grandchild of O."],
  [199, "Blood Relations", "FAST ET", "Medium", "Pointing to a woman, a man says: 'Her husband is my father's only son.' Woman to man?", ["Wife", "Sister", "Aunt", "Mother"], 0, "Father's only son is the man himself. Woman is his wife."],
  [200, "Blood Relations", "NTC", "Medium", "Pointing to a girl, a boy says: 'Her brother is my father's only son.' Girl to boy?", ["Sister", "Wife", "Aunt", "Mother"], 0, "Father's only son is the boy. So the girl is his sister."],

  // ─── BATCH 5: Q201 to Q250 ───
  [201, "Blood Relations", "ISSB", "Hard", "X is aunt of Y. Y is son of Z. Z is husband of W. X to Z?", ["Sister", "Sister-in-law", "Cousin", "Aunt"], 0, "X is sister (or sister-in-law) of Z."],
  [202, "Blood Relations", "NET", "Hard", "M is grandmother of N. N is daughter of O. O is wife of P. M to O?", ["Mother", "Mother-in-law", "Aunt", "Sister"], 0, "M is the mother of O."],
  [203, "Blood Relations", "MDCAT", "Hard", "If P$Q means P is mother of Q; P#Q means P is father of Q. Which means A is grandmother of B?", ["A$C#B", "A#C$B", "A@C#B", "A$C@B"], 0, "A is mother of C, C is father of B → A$C#B."],
  [204, "Blood Relations", "FAST ET", "Hard", "If D+E means D is sister of E; D-E means D is brother of E; D*E means D is mother of E. Which means P is aunt of Q?", ["P+R*Q", "P-R*Q", "P*R+Q", "P*R-Q"], 0, "P is sister of R, R is mother of Q → P+R*Q."],
  [205, "Blood Relations", "NTC", "Medium", "'She is the daughter of my grandmother's only child.' Relation to speaker?", ["Sister", "Cousin", "Aunt", "Niece"], 0, "Grandmother's only child is mother/father; daughter is sister."],
  [206, "Blood Relations", "ISSB", "Medium", "'She is the wife of my father's only son.' Relation to speaker (female)?", ["Sister-in-law", "Sister", "Aunt", "Cousin"], 0, "Father's only son is brother; his wife is sister-in-law."],
  [207, "Blood Relations", "NET", "Hard", "B's mother's brother's mother's daughter is?", ["Aunt/Mother", "Sister", "Cousin", "Grandmother"], 0, "B's aunt or mother."],
  [208, "Blood Relations", "MDCAT", "Hard", "D's sister's mother's sister's daughter is?", ["Cousin", "Sister", "Aunt", "Niece"], 0, "D's cousin."],
  [209, "Blood Relations", "FAST ET", "Hard", "A is brother of R. C is mother of B. M is sister of C. How is M related to B?", ["Aunt", "Mother", "Sister", "Niece"], 0, "M is the aunt of B."],
  [210, "Blood Relations", "NTC", "Hard", "X is Y's sister. Z is Y's brother. W is Z's son. How is X related to W?", ["Aunt", "Mother", "Sister", "Niece"], 0, "X is the aunt of W."],
  [211, "Blood Relations", "ISSB", "Hard", "Pointing to an old man, Kailash said: 'His son is my son's uncle.' Kailash to man?", ["Son", "Brother", "Father", "Uncle"], 0, "Kailash is the son of the man."],
  [212, "Blood Relations", "NET", "Hard", "Pointing to a boy, Reena said: 'He is the only son of the only child of my grandfather.' Boy to Reena?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Grandfather's only child is father; only son is brother."],
  [213, "Blood Relations", "MDCAT", "Hard", "Q is the son of P. X is the daughter of Q. R is the aunty of X. What is L to P?", ["Grandson", "Son", "Nephew", "Brother"], 0, "L is grandson of P."],
  [214, "Blood Relations", "FAST ET", "Hard", "M and F are married couple. A and B are sisters. A is sister of F. Who is B to M?", ["Sister-in-law", "Sister", "Niece", "Daughter"], 0, "B is sister-in-law of M."],
  [215, "Blood Relations", "NTC", "Hard", "If M-N means M is brother of N; M/N means M is mother of N. How is A related to B in A-C/B?", ["Uncle", "Father", "Brother", "Nephew"], 0, "A is uncle of B."],
  [216, "Blood Relations", "ISSB", "Hard", "If J/K means J is son of K; J-K means J is sister of K; J+K means J is mother of K. A to B in A-C+B?", ["Aunt", "Mother", "Sister", "Grandmother"], 0, "A is aunt of B."],
  [217, "Blood Relations", "NET", "Hard", "Read: A+B=father, A-B=mother, AB=brother, A/B=sister. W-XY/Z. W to Z?", ["Mother", "Grandmother", "Aunt", "Sister"], 0, "W is mother of Z."],
  [218, "Blood Relations", "MDCAT", "Hard", "Read: A+B=father, A-B=mother, AB=brother. CD/E-F. C to F?", ["Uncle", "Father", "Grandfather", "Brother"], 0, "C is uncle of F."],
  [219, "Blood Relations", "FAST ET", "Hard", "Introducing a girl, a boy says: 'She is the daughter of the son of the mother of my aunt.' Girl to boy?", ["Sister/Cousin", "Mother", "Aunt", "Niece"], 0, "Girl is sister or cousin of the boy."],
  [220, "Blood Relations", "NTC", "Hard", "Introducing a woman, a man says: 'She is the mother of the brother of the son of my wife.' Woman to man?", ["Wife", "Sister", "Mother", "Daughter"], 0, "Son of wife is man's son; mother is wife."],
  [221, "Blood Relations", "ISSB", "Hard", "X's mother Y is sister of Z's father W. How is Y related to Z?", ["Aunt", "Mother", "Sister", "Niece"], 0, "Y is the aunt of Z."],
  [222, "Blood Relations", "NET", "Hard", "M's sister N is daughter of O's brother P. How is N related to O?", ["Niece", "Daughter", "Sister", "Aunt"], 0, "N is the niece of O."],
  [223, "Blood Relations", "MDCAT", "Hard", "A family has 1 grandfather, 1 grandmother, 2 fathers, 2 mothers, 4 children, 3 grandchildren. Minimum people?", ["7", "8", "9", "10"], 0, "Minimum number of people required is 7."],
  [224, "Blood Relations", "FAST ET", "Hard", "P, Q, R, S, T, U are family. P is doctor, Q nurse, R P's son, S Q's mother, T R's sister, U S's husband. U to T?", ["Grandfather", "Father", "Uncle", "Brother"], 0, "U is the grandfather of T."],
  [225, "Blood Relations", "NTC", "Medium", "Man points to woman: 'She is the daughter of my wife's mother's only son.' Relation?", ["Niece", "Daughter", "Sister", "Aunt"], 0, "Wife's mother's only son is brother-in-law; daughter is niece."],
  [226, "Blood Relations", "ISSB", "Medium", "Boy points to girl: 'She is the sister of my father's mother's only grandson.' Relation?", ["Sister", "Cousin", "Aunt", "Niece"], 0, "Father's mother's only grandson is boy; sister is sister."],
  [227, "Blood Relations", "NET", "Hard", "X is sister of Y. Y is sister of Z. Z is wife of W. V is mother of X. W to V?", ["Son-in-law", "Son", "Brother", "Uncle"], 0, "W is the son-in-law of V."],
  [228, "Blood Relations", "MDCAT", "Hard", "M is daughter of N. N is daughter of O. O is wife of P. Q is father of M. P to Q?", ["Father-in-law", "Father", "Grandfather", "Uncle"], 0, "P is the father-in-law of Q."],
  [229, "Blood Relations", "FAST ET", "Hard", "A+B=father, A-B=mother, A*B=brother, A/B=sister. W#X+Y/Z. W to Z?", ["Mother", "Grandmother", "Aunt", "Sister"], 0, "W is grandmother of Z."],
  [230, "Blood Relations", "NTC", "Hard", "A+B=father, A-B=mother, C/D#E+F. C to F?", ["Aunt", "Mother", "Grandmother", "Sister"], 0, "C is aunt of F."],
  [231, "Blood Relations", "ISSB", "Medium", "My mother's only sister's husband's only son's sister is my?", ["Cousin", "Sister", "Niece", "Aunt"], 0, "Aunt's daughter is cousin."],
  [232, "Blood Relations", "NET", "Medium", "My sister's only brother's wife's only son's sister is my?", ["Niece", "Daughter", "Cousin", "Sister"], 0, "Sister's only brother is myself; wife's daughter is my daughter/niece."],
  [233, "Blood Relations", "MDCAT", "Hard", "X is Y's aunt. Y is Z's sister. Z is W's daughter. W is V's husband. X to V?", ["Sister-in-law", "Sister", "Cousin", "Aunt"], 0, "X is sister-in-law of V."],
  [234, "Blood Relations", "FAST ET", "Hard", "M is N's grandmother. N is O's sister. O is P's daughter. P is Q's husband. M to Q?", ["Mother-in-law", "Mother", "Aunt", "Sister"], 0, "M is mother-in-law of Q."],
  [235, "Blood Relations", "NTC", "Hard", "Man points to woman: 'Her father's sister's mother's only son is my father.' Man to woman?", ["Cousin", "Brother", "Uncle", "Nephew"], 0, "They are cousins."],
  [236, "Blood Relations", "ISSB", "Hard", "Girl to boy: 'Her brother's father's sister's only son is my brother.' Girl to boy?", ["Cousin", "Sister", "Aunt", "Niece"], 0, "Girl is cousin of boy."],
  [237, "Blood Relations", "NET", "Medium", "X is Y's father's sister's only brother's daughter. X to Y?", ["Sister", "Cousin", "Niece", "Aunt"], 0, "Father's sister's only brother is father; daughter is sister."],
  [238, "Blood Relations", "MDCAT", "Medium", "M is N's father's brother's only sister's daughter. M to N?", ["Cousin", "Sister", "Niece", "Aunt"], 0, "They are cousins."],
  [239, "Blood Relations", "FAST ET", "Medium", "G is H's mother's father's only daughter's son. G to H?", ["Brother", "Cousin", "Nephew", "Uncle"], 0, "Mother's father's only daughter is mother; her son is brother."],
  [240, "Blood Relations", "NTC", "Easy", "A is B's brother. C is B's father. A to C?", ["Son", "Nephew", "Brother", "Uncle"], 0, "A is the son of C."],
  [241, "Blood Relations", "ISSB", "Easy", "P is Q's father. R is Q's sister. P to R?", ["Father", "Uncle", "Brother", "Grandfather"], 0, "P is the father of R."],
  [242, "Blood Relations", "NET", "Easy", "G is H's son. I is H's wife. G to I?", ["Son", "Nephew", "Brother", "Uncle"], 0, "G is the son of I."],
  [243, "Number & Letter Series", "MDCAT", "Easy", "Next in series: 10, 20, 30, 40, ?", ["45", "50", "55", "60"], 1, "Add +10: 40 + 10 = 50."],
  [244, "Number & Letter Series", "FAST ET", "Easy", "Missing term: 3, 8, 15, 24, ?", ["30", "33", "35", "38"], 2, "Pattern n² - 1: 6² - 1 = 35."],
  [245, "Number & Letter Series", "NTC", "Medium", "Find the odd one out: 12, 24, 36, 45, 48", ["24", "36", "45", "48"], 2, "45 is not divisible by 12."],
  [246, "Number & Letter Series", "ISSB", "Hard", "Next in series: 24, 30, 36, 40", ["24", "30", "36", "40"], 1, "Sequence pattern step → 30."],
  [247, "Number & Letter Series", "NET", "Easy", "Next in series: B, D, F, H, ?", ["I", "J", "K", "L"], 1, "Skip 1 letter (+2 positions) → J."],
  [248, "Number & Letter Series", "MDCAT", "Medium", "Next in series: C, F, I, L, ?", ["O", "P", "Q", "M"], 0, "Skip 2 letters (+3 positions) → O."],
  [249, "Number & Letter Series", "FAST ET", "Hard", "Next in series: A1, B2, C3, D4, ?", ["E4", "F5", "E5", "E6"], 2, "Letter + number position → E5."],
  [250, "Number & Letter Series", "NTC", "Easy", "Complete: JAK, KBL, LCM, MDN, ___", ["NEO", "OEP", "MEN", "PFQ"], 0, "1st letters J,K,L,M,N; middle A,B,C,D,E; 3rd K,L,M,N,O → NEO."],

  // ─── BATCH 6: Q251 to Q300 ───
  [251, "Number & Letter Series", "ISSB", "Medium", "Complete: DEF, DEF2, DE2F2, ___, D2E2F3", ["DEF3", "D2E2F2", "DE2F3", "D2E3F"], 2, "Sequence pattern → DE2F3."],
  [252, "Number & Letter Series", "NET", "Hard", "Missing term: C4X, F9U, I16R, ?", ["L25P", "L25O", "K25P", "L27O"], 1, "1st (+3), middle (squares 2²,3²,4²,5²=25), 3rd (-3) → L25O."],
  [253, "Number & Letter Series", "MDCAT", "Easy", "Next in series: 53, 53, 40, 40, 27, 27, ?", ["12", "14", "27", "53"], 1, "Repeated numbers subtract 13: 27 - 13 = 14."],
  [254, "Number & Letter Series", "FAST ET", "Medium", "Next in series: 1.5, 2.3, 3.1, 3.9, ?", ["4.2", "4.4", "4.7", "5.1"], 2, "Add +0.8: 3.9 + 0.8 = 4.7."],
  [255, "Number & Letter Series", "NTC", "Hard", "What comes next: 10, 14, 26, 42, 70, ?", ["100", "102", "106", "114"], 3, "Fibonacci-like sum pattern → 114."],
  [256, "Number & Letter Series", "ISSB", "Easy", "Series: D, H, L, P, T, X, ?", ["A", "B", "C", "D"], 1, "Step of +4 positions: X (+4) = B."],
  [257, "Number & Letter Series", "NET", "Medium", "Series: V, S, P, M, J, G, ?", ["D", "C", "B", "E"], 0, "Step back by -3 positions: G (-3) = D."],
  [258, "Number & Letter Series", "MDCAT", "Hard", "Series: ZY, XW, VU, TS, ?", ["RQ", "PO", "NM", "LK"], 0, "Pairs of reverse consecutive letters → RQ."],
  [259, "Number & Letter Series", "FAST ET", "Easy", "10, 20, 40, 80, 160, ?", ["200", "240", "320", "280"], 2, "Doubling sequence: 160 × 2 = 320."],
  [260, "Number & Letter Series", "NTC", "Medium", "2.5, 5, 10, 20, 40, ?", ["60", "80", "100", "120"], 1, "Doubling sequence: 40 × 2 = 80."],
  [261, "Number & Letter Series", "ISSB", "Hard", "4, 9, 25, 49, 121, ?", ["144", "169", "196", "225"], 1, "Squares of prime numbers: 13² = 169."],
  [262, "Number & Letter Series", "NET", "Easy", "5, 11, 23, 47, 95, ?", ["190", "191", "192", "193"], 1, "Pattern ×2 + 1: 95 × 2 + 1 = 191."],
  [263, "Number & Letter Series", "MDCAT", "Medium", "1, 4, 13, 40, 121, ?", ["362", "363", "364", "365"], 2, "Pattern ×3 + 1: 121 × 3 + 1 = 364."],
  [264, "Number & Letter Series", "FAST ET", "Hard", "4, 13, 40, 121, 364, ?", ["1093", "1094", "1095", "1096"], 0, "Pattern ×3 + 1: 364 × 3 + 1 = 1093."],
  [265, "Number & Letter Series", "NTC", "Easy", "C, X, E, V, G, ?", ["T", "R", "S", "Q"], 0, "Opposite letter of G is T."],
  [266, "Coding & Decoding", "ISSB", "Easy", "If RUN is SVO, WAL is?", ["XBM", "YCN", "ZDO", "AEP"], 0, "Shift +1 each letter → XBM."],
  [267, "Coding & Decoding", "NET", "Medium", "If MAP is NBO, SET is?", ["TFU", "UGV", "VHW", "WIX"], 0, "Shift +1 each letter → TFU."],
  [268, "Coding & Decoding", "MDCAT", "Hard", "If WATER = YCVGT, FIRE = ?", ["HKTH", "HKUG", "GKUG", "HKTG"], 3, "Shift +2 each letter → HKTG."],
  [269, "Coding & Decoding", "FAST ET", "Easy", "If PIN is 39, TIN is?", ["43", "44", "45", "47"], 0, "T(20)+I(9)+N(14) = 43."],
  [270, "Coding & Decoding", "NTC", "Medium", "If TOY is 60, JOY is?", ["45", "48", "50", "52"], 2, "J(10)+O(15)+Y(25) = 50."],
  [271, "Coding & Decoding", "ISSB", "Hard", "If ENGLAND is 1234526, FRANCE is 785291, GREECE is?", ["381191", "381192", "381193", "381194"], 0, "Direct letter substitution → 381191."],
  [272, "Coding & Decoding", "NET", "Easy", "If COLD = DPME, WARM = ?", ["XBSN", "XCSO", "XCTN", "XCTO"], 0, "Shift +1 each letter → XBSN."],
  [273, "Coding & Decoding", "MDCAT", "Medium", "If PEACH = QFBDJ, MELON = ?", ["NFMPO", "NFNPO", "NEMPO", "NFMPP"], 1, "Shift +1 each letter → NFNPO."],
  [274, "Coding & Decoding", "FAST ET", "Hard", "If 'pen' is 'pencil', 'pencil' is 'eraser', 'eraser' is 'book', what removes pencil marks?", ["pen", "pencil", "eraser", "book"], 3, "Eraser removes pencil marks, and eraser is 'book'."],
  [275, "Coding & Decoding", "NTC", "Easy", "A=0, B=1, C=2... BAT = ?", ["20", "21", "22", "23"], 1, "B(1)+A(0)+T(19) = 20 (or 21)."],
  [276, "Coding & Decoding", "ISSB", "Medium", "If '246' is 'red apple sweet', '681' is 'sweet green mango', what is 'sweet'?", ["2", "4", "6", "8"], 2, "Common digit for sweet is 6."],
  [277, "Coding & Decoding", "NET", "Hard", "If 'sun is hot' is '9 8 7', 'hot and cold' is '7 6 5', what is 'hot'?", ["9", "8", "7", "6"], 2, "Common digit for hot is 7."],
  [278, "Coding & Decoding", "MDCAT", "Easy", "If CLOUD is DMPVE, RAIN is?", ["SBJO", "SBJP", "SCJO", "SCJP"], 0, "Shift +1 each letter → SBJO."],
  [279, "Coding & Decoding", "FAST ET", "Medium", "If HORSE is FMRQC, TIGER is?", ["RGECP", "RHECP", "RGECQ", "RHECQ"], 0, "Shift pattern → RGECP."],
  [280, "Coding & Decoding", "NTC", "Hard", "If BLACK is YOZXP, WHITE is?", ["DSRGV", "DSRGW", "DTRGV", "DTRGW"], 0, "Opposite alphabet letters → DSRGV."],
  [281, "Coding & Decoding", "ISSB", "Easy", "Code P as 1, E as 2, N as 3. PEN is?", ["123", "231", "312", "132"], 0, "Direct position substitution → 123."],
  [282, "Coding & Decoding", "NET", "Medium", "Code M=4, N=8, O=12. P=?", ["14", "15", "16", "17"], 2, "Multiples of 4: P = 4 × 4 = 16."],
  [283, "Coding & Decoding", "MDCAT", "Hard", "Code CAN as 3114, PAN as?", ["16114", "16115", "16116", "16117"], 0, "P(16) A(1) N(14) → 16114."],
  [284, "Coding & Decoding", "FAST ET", "Easy", "Code SUN as &%, FUN as @%. S is?", ["&", "*", "%", "@"], 0, "Symbol for S is &."],
  [285, "Coding & Decoding", "NTC", "Medium", "Code PLANT as %^&*(, ANTL is?", ["&*(%", "&*(^", "&*^(", "&*^%"], 1, "Symbol rearrangement → &*(^."],
  [286, "Coding & Decoding", "ISSB", "Hard", "If W=23, WE=28, then WENT=?", ["55", "56", "57", "58"], 1, "Sum of positions → 56."],
  [287, "Coding & Decoding", "NET", "Easy", "Code JUMP as KVNQ, WALK as?", ["XBML", "XAML", "XBMM", "XAMM"], 0, "Shift +1 each letter → XBML."],
  [288, "Coding & Decoding", "MDCAT", "Medium", "If BREAD is 2-18-5-1-4, BUTTER is?", ["2-21-20-20-5-18", "2-21-20-20-5-19", "2-21-20-20-6-18", "2-21-20-20-6-19"], 0, "Alphabet positions B(2)-U(21)-T(20)-T(20)-E(5)-R(18)."],
  [289, "Coding & Decoding", "FAST ET", "Hard", "If CAR = 3, BIKE = 4, AEROPLANE = ?", ["7", "8", "9", "10"], 2, "Number of letters in AEROPLANE = 9."],
  [290, "Coding & Decoding", "NTC", "Easy", "If L=11, M=12, N=13. O=?", ["13", "14", "15", "16"], 1, "Position count minus 1: O = 15 - 1 = 14."],
  [291, "Direction Sense Tests", "ISSB", "Easy", "Walk 8km West, turn South 6km. Distance?", ["8km", "10km", "12km", "14km"], 1, "d = √(8² + 6²) = 10 km."],
  [292, "Direction Sense Tests", "NET", "Medium", "Face West, turn 90° CW. Facing?", ["North", "South", "East", "North-West"], 0, "90° CW from West is North."],
  [293, "Direction Sense Tests", "MDCAT", "Hard", "Face West, turn 90° CW, then 135° CCW. Facing?", ["SW", "NW", "SE", "NE"], 0, "90° CW - 135° CCW = 45° CCW from West → South-West."],
  [294, "Direction Sense Tests", "FAST ET", "Easy", "M is West of N. O is South of N. M to O?", ["NW", "NE", "SW", "SE"], 0, "M relative to O is North-West."],
  [295, "Direction Sense Tests", "NTC", "Medium", "Walk 5km W, turn L 5km, turn L 5km. Distance?", ["5km", "10km", "15km", "20km"], 0, "Distance from start is 5km South."],
  [296, "Direction Sense Tests", "ISSB", "Hard", "Evening shadow falls to the left. Facing?", ["North", "South", "East", "West"], 1, "Sun is West; shadow falls East (left) when facing South."],
  [297, "Direction Sense Tests", "NET", "Easy", "Move 6m W, 6m S, 6m E. Where from start?", ["6m E", "6m W", "6m N", "6m S"], 3, "6 meters South of start."],
  [298, "Direction Sense Tests", "MDCAT", "Medium", "Turn 180° CW, then 90° CCW. Facing?", ["Right", "Left", "Same", "Opposite"], 0, "Net 90° CW turn (Right)."],
  [299, "Direction Sense Tests", "FAST ET", "Hard", "If West becomes NW, what does South become?", ["SW", "SE", "NE", "NW"], 0, "45° CW shift: South becomes South-West."],
  [300, "Direction Sense Tests", "NTC", "Easy", "Clock shows 12:00. Minute hand points N. Hour hand points?", ["N", "S", "E", "W"], 0, "Hour hand at 12 points North."],

  // ─── BATCH 7: Q301 to Q350 ───
  [301, "Direction Sense Tests", "ISSB", "Medium", "Walk 5km W, 1km S, 5km E. Distance from start?", ["1km", "2km", "3km", "4km"], 0, "Displacement is 1km South."],
  [302, "Direction Sense Tests", "NET", "Hard", "M is 12m W of N. O is 5m S of N. Distance M to O?", ["10m", "11m", "12m", "13m"], 3, "d = √(12² + 5²) = 13 m."],
  [303, "Direction Sense Tests", "MDCAT", "Easy", "Moving W, take 2 right turns. Facing?", ["E", "W", "N", "S"], 0, "180° rotation → East."],
  [304, "Direction Sense Tests", "FAST ET", "Medium", "In evening, M & N face each other. M's shadow is behind M. N faces?", ["E", "W", "N", "S"], 0, "M faces West (shadow behind East), so N faces East."],
  [305, "Direction Sense Tests", "NTC", "Hard", "Walk 4km W, 4km S, 4km E, 4km N. Final position?", ["4km W", "4km S", "4km N", "Start point"], 3, "Returns to starting point."],
  [306, "Direction Sense Tests", "ISSB", "Easy", "Walk 8m W, turn 180°, walk 10m. Where from start?", ["2m E", "2m W", "18m E", "18m W"], 0, "8m W - 10m E = 2m East of start."],
  [307, "Direction Sense Tests", "NET", "Medium", "Face S, turn 45° CCW, then 90° CW. Facing?", ["SW", "SE", "NW", "NE"], 0, "Net 45° CW from South → South-West."],
  [308, "Direction Sense Tests", "MDCAT", "Hard", "From M, N is W. From N, O is N. From M, O is?", ["NW", "NE", "SW", "SE"], 0, "Relative direction is North-West."],
  [309, "Direction Sense Tests", "FAST ET", "Easy", "Start W, take R, then R, then L. Facing?", ["N", "S", "E", "W"], 0, "West → Right (N) → Right (E) → Left (N)."],
  [310, "Direction Sense Tests", "NTC", "Medium", "Clock 3:45. Minute hand points W. Hour hand points?", ["E", "W", "N", "S"], 0, "Hour hand at 3 points East."],
  [311, "Direction Sense Tests", "ISSB", "Hard", "Walk 4km W, 4km NW. General direction from start?", ["NW", "NE", "SW", "SE"], 0, "General direction is North-West."],
  [312, "Direction Sense Tests", "NET", "Easy", "Map: Top is N, Right is E. Bottom is?", ["S", "N", "W", "E"], 0, "Opposite of North is South."],
  [313, "Direction Sense Tests", "MDCAT", "Medium", "I face W. Turn 90° CW, walk 6m, turn 90° CW, walk 8m. Distance?", ["10m", "14m", "2m", "12m"], 0, "d = √(6² + 8²) = 10 m."],
  [314, "Direction Sense Tests", "FAST ET", "Hard", "Go 6km W, then 6km N, then 6km NW. Final direction?", ["NW", "NE", "SW", "SE"], 0, "Final direction is North-West."],
  [315, "Direction Sense Tests", "NTC", "Easy", "Walk 4km W, 5km N, 6km E, 7km S. General direction?", ["SE", "SW", "NE", "NW"], 0, "Displacement (+2 East, -2 South) → South-East."],
  [316, "Blood Relations", "ISSB", "Easy", "M is N's mother. O is N's brother. M to O?", ["Mother", "Aunt", "Sister", "Grandmother"], 0, "M is the mother of O."],
  [317, "Blood Relations", "NET", "Medium", "Pointing to a girl, Mary says: 'She is the daughter of my father's only daughter.' Girl to Mary?", ["Daughter", "Niece", "Sister", "Mother"], 0, "Father's only daughter is Mary. So the girl is her daughter."],
  [318, "Blood Relations", "MDCAT", "Hard", "A&B means A is son of B. AB means A is daughter of B. What is P&QR?", ["P is grandson of R", "P is granddaughter of R", "P is son of R", "P is brother of R"], 0, "P is grandson of R."],
  [319, "Blood Relations", "FAST ET", "Easy", "M's brother is son of N. N's brother is O. M to O?", ["Nephew/Niece", "Grandchild", "Son/Daughter", "Brother/Sister"], 0, "M is nephew/niece of O."],
  [320, "Blood Relations", "NTC", "Medium", "M is N's mother. O is M's mother. P is O's mother. Q is P's mother. N to O?", ["Grandchild", "Child", "Great-grandchild", "Niece"], 0, "N is the grandchild of O."],
  [321, "Blood Relations", "ISSB", "Hard", "Pointing to a girl, a boy says: 'Her brother is my father's only son.' Girl to boy?", ["Sister", "Wife", "Aunt", "Mother"], 0, "Father's only son is the boy. So the girl is his sister."],
  [322, "Blood Relations", "NET", "Easy", "M is grandmother of N. N is daughter of O. O is wife of P. M to O?", ["Mother", "Mother-in-law", "Aunt", "Sister"], 0, "M is the mother of O."],
  [323, "Blood Relations", "MDCAT", "Medium", "If D+E means D is sister of E; D-E means D is brother of E; D*E means D is mother of E. Which means P is aunt of Q?", ["P+R*Q", "P-R*Q", "P*R+Q", "P*R-Q"], 0, "P is sister of R, R is mother of Q → P+R*Q."],
  [324, "Blood Relations", "FAST ET", "Hard", "'She is the wife of my father's only son.' Relation to speaker (female)?", ["Sister-in-law", "Sister", "Aunt", "Cousin"], 0, "Father's only son is brother; his wife is sister-in-law."],
  [325, "Blood Relations", "NTC", "Easy", "D's sister's mother's sister's daughter is?", ["Cousin", "Sister", "Aunt", "Niece"], 0, "D's cousin."],
  [326, "Blood Relations", "ISSB", "Medium", "X is Y's sister. Aunt, Mother, Sister, Niece?", ["Aunt", "Mother", "Sister", "Niece"], 0, "X is aunt."],
  [327, "Blood Relations", "NET", "Hard", "Pointing to a boy in the photograph, Reena said: 'He is the only son of the only child of my grandfather.' Boy to Reena?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Boy is her brother."],
  [328, "Blood Relations", "MDCAT", "Easy", "M and F are a married couple. A and B are sisters. A is the sister of F. Who is B to M?", ["Sister-in-law", "Sister", "Niece", "Daughter"], 0, "B is sister-in-law of M."],
  [329, "Blood Relations", "FAST ET", "Medium", "If J/K means J is son of K; J-K means J is sister of K; J+K means J is mother of K. How is A related to B in A-C+B?", ["Aunt", "Mother", "Sister", "Grandmother"], 0, "A is aunt of B."],
  [330, "Blood Relations", "NTC", "Hard", "Read: A+B=father, A-B=mother, AB=brother, A/B=sister. CD/E-F. C to F?", ["Uncle", "Father", "Grandfather", "Brother"], 0, "C is uncle of F."],
  [331, "Blood Relations", "ISSB", "Easy", "Introducing a woman, a man says: 'She is the mother of the brother of the son of my wife.' Woman to man?", ["Wife", "Sister", "Mother", "Daughter"], 0, "Woman is his wife."],
  [332, "Blood Relations", "NET", "Medium", "M's sister N is daughter of O's brother P. How is N related to O?", ["Niece", "Daughter", "Sister", "Aunt"], 0, "N is the niece of O."],
  [333, "Blood Relations", "MDCAT", "Hard", "P, Q, R, S, T, U are family. P is doctor. Q is nurse. R is P's son. S is Q's mother. T is R's sister. U is S's husband. Professions aside, how is U related to T?", ["Grandfather", "Father", "Uncle", "Brother"], 0, "U is the grandfather of T."],
  [334, "Blood Relations", "FAST ET", "Easy", "Boy points to girl: 'She is the sister of my father's mother's only grandson.' Relation?", ["Sister", "Cousin", "Aunt", "Niece"], 0, "She is his sister."],
  [335, "Blood Relations", "NTC", "Medium", "M is daughter of N. N is daughter of O. O is wife of P. Q is father of M. P is related to Q as?", ["Father-in-law", "Father", "Grandfather", "Uncle"], 0, "P is father-in-law of Q."],
  [336, "Blood Relations", "ISSB", "Hard", "A+B=father, A-B=mother, A*B=brother, A/B=sister, A$B=husband, A#B=wife. C/D#E+F. C to F?", ["Aunt", "Mother", "Grandmother", "Sister"], 0, "C is aunt of F."],
  [337, "Blood Relations", "NET", "Easy", "My sister's only brother's wife's only son's sister is?", ["Niece", "Daughter", "Cousin", "Sister"], 0, "She is niece."],
  [338, "Blood Relations", "MDCAT", "Medium", "M is N's grandmother. N is O's sister. O is P's daughter. P is Q's husband. M to Q?", ["Mother-in-law", "Mother", "Aunt", "Sister"], 0, "M is mother-in-law of Q."],
  [339, "Blood Relations", "FAST ET", "Hard", "Pointing to a girl, a boy says: 'Her brother's father's sister's only son is my brother.' Girl to boy?", ["Cousin", "Sister", "Aunt", "Niece"], 0, "Girl is cousin of boy."],
  [340, "Blood Relations", "NTC", "Easy", "M is N's father's brother's only sister's daughter. M to N?", ["Cousin", "Sister", "Niece", "Aunt"], 0, "M is cousin of N."],
  [341, "Number & Letter Series", "ISSB", "Easy", "Next in series: 3, 6, 9, 12, ?", ["15", "18", "21", "24"], 0, "Add +3: 12 + 3 = 15."],
  [342, "Number & Letter Series", "NET", "Easy", "Missing term: 0, 3, 8, 15, ?", ["24", "25", "26", "20"], 0, "Pattern n² - 1: 5² - 1 = 24."],
  [343, "Number & Letter Series", "MDCAT", "Medium", "Find the odd one out: 8, 27, 64, 100, 125", ["27", "64", "100", "125"], 2, "100 is not a perfect cube."],
  [344, "Number & Letter Series", "FAST ET", "Hard", "Next in series: 3, 4, 12, 39, 103, ?", ["228", "250", "213", "312"], 0, "Pattern +1³, +2³, +3³, +4³, +5³: 103 + 125 = 228."],
  [345, "Number & Letter Series", "NTC", "Easy", "Next in series: A, D, G, J, ?", ["M", "N", "O", "L"], 0, "Skip 2 letters (+3 positions): J (+3) = M."],
  [346, "Number & Letter Series", "ISSB", "Medium", "Next in series: B, E, H, K, ?", ["M", "N", "O", "P"], 1, "Skip 2 letters (+3 positions): K (+3) = N."],
  [347, "Number & Letter Series", "NET", "Hard", "Next in series: A, C, F, J, O, ?", ["S", "T", "U", "V"], 2, "Gaps +2, +3, +4, +5, +6: O (+6) = U."],
  [348, "Number & Letter Series", "MDCAT", "Easy", "Complete: HGF, CAB, JKL, GHI", ["HGF", "CAB", "JKL", "GHI"], 0, "3 reverse letters block → HGF."],
  [349, "Number & Letter Series", "FAST ET", "Medium", "Complete: DEF, DEF2, DE2F2, ___, D2E2F3", ["DEF3", "D2E2F2", "DE2F3", "D2E3F"], 2, "Sequence pattern → DE2F3."],
  [350, "Number & Letter Series", "NTC", "Hard", "Missing term: 3F, 6G, 11I, 18L, ?", ["21O", "25N", "27P", "27O"], 2, "Numbers +3,+5,+7,+9=27; letters +1,+2,+3,+4=P → 27P."],

  // ─── BATCH 8: Q351 to Q400 ───
  [351, "Number & Letter Series", "ISSB", "Easy", "Next in series: 22, 21, 23, 22, 24, 23, ?", ["22", "24", "25", "26"], 2, "Alternating -1, +2, -1, +2, -1, +2: 23 + 2 = 25."],
  [352, "Number & Letter Series", "NET", "Medium", "Next in series: 1.5, 2.3, 3.1, 3.9, ?", ["4.2", "4.4", "4.7", "5.1"], 2, "Add +0.8: 3.9 + 0.8 = 4.7."],
  [353, "Number & Letter Series", "MDCAT", "Hard", "What comes next: 5, 9, 16, 29, 54, ?", ["103", "105", "109", "112"], 0, "Pattern ×2 - 1, ×2 - 2, ×2 - 3, ×2 - 4: 54×2 - 5 = 103."],
  [354, "Number & Letter Series", "FAST ET", "Easy", "Series: C, G, K, O, S, W, ?", ["Z", "Y", "X", "A"], 3, "Skip 3 letters (+4 positions): W (+4) = A."],
  [355, "Number & Letter Series", "NTC", "Medium", "Series: W, T, Q, N, K, H, ?", ["E", "D", "C", "F"], 0, "Step back by -3 positions: H (-3) = E."],
  [356, "Number & Letter Series", "ISSB", "Hard", "Series: ZY, XW, VU, TS, ?", ["RQ", "PO", "NM", "LK"], 0, "Pairs of reverse consecutive letters → RQ."],
  [357, "Number & Letter Series", "NET", "Easy", "5, 10, 20, 40, 80, 160, ?", ["240", "320", "300", "400"], 1, "Doubling sequence: 160 × 2 = 320."],
  [358, "Number & Letter Series", "MDCAT", "Medium", "1.5, 3, 6, 12, 24, ?", ["36", "48", "72", "96"], 1, "Doubling sequence: 24 × 2 = 48."],
  [359, "Number & Letter Series", "FAST ET", "Hard", "1, 2, 2, 4, 8, 32, ?", ["256", "128", "64", "512"], 0, "Product of previous two terms: 8 × 32 = 256."],
  [360, "Number & Letter Series", "NTC", "Easy", "4, 9, 19, 39, 79, ?", ["158", "159", "160", "161"], 1, "Pattern ×2 + 1: 79 × 2 + 1 = 159."],
  [361, "Number & Letter Series", "ISSB", "Medium", "10, 21, 43, 87, 175, ?", ["350", "351", "352", "353"], 1, "Pattern ×2 + 1: 175 × 2 + 1 = 351."],
  [362, "Number & Letter Series", "NET", "Hard", "4, 13, 40, 121, 364, ?", ["1093", "1094", "1095", "1096"], 0, "Pattern ×3 + 1: 364 × 3 + 1 = 1093."],
  [363, "Number & Letter Series", "MDCAT", "Easy", "B, Y, D, W, F, ?", ["T", "S", "U", "V"], 2, "Forward/reverse positions (B-2, Y-25, D-4, W-23, F-6, U-21) → U."],
  [364, "Coding & Decoding", "FAST ET", "Easy", "If A=1, B=2, code for CAB?", ["312", "321", "123", "213"], 0, "C=3, A=1, B=2 → 312."],
  [365, "Coding & Decoding", "NTC", "Medium", "If MAP is NBO, SET is?", ["TFU", "UGV", "VHW", "WIX"], 0, "Shift +1 each letter → TFU."],
  [366, "Coding & Decoding", "ISSB", "Hard", "If CAT = FDW, DOG = ?", ["GRK", "GRJ", "HRJ", "IRK"], 1, "Shift +3 each letter → GRJ."],
  [367, "Coding & Decoding", "NET", "Easy", "If GO is 22, COME is?", ["35", "36", "37", "38"], 1, "Sum of positions: C(3)+O(15)+M(13)+E(5) = 36."],
  [368, "Coding & Decoding", "MDCAT", "Medium", "If BOY is 42, GIRL is?", ["46", "47", "48", "49"], 0, "Sum of positions: G(7)+I(9)+R(18)+L(12) = 46."],
  [369, "Coding & Decoding", "FAST ET", "Hard", "If Z = 52 and ACT = 48, then BAT = ?", ["39", "41", "44", "46"], 3, "2 × (2+1+20) = 46."],
  [370, "Coding & Decoding", "NTC", "Easy", "If ROAD = URDG, SWAN = ?", ["VZAN", "VZDQ", "VZDN", "WZAN"], 1, "Shift +3 each letter → VZDQ."],
  [371, "Coding & Decoding", "ISSB", "Medium", "If GRAPE = HQBQF, LEMON = ?", ["MFNPO", "MFOPP", "MFOOP", "MFNOO"], 0, "Shift +1 each letter → MFNPO."],
  [372, "Coding & Decoding", "NET", "Hard", "If 'red' is 'green', 'green' is 'yellow', 'yellow' is 'blue', blood color is?", ["red", "green", "yellow", "blue"], 1, "Blood is red, and 'red' is 'green'."],
  [373, "Coding & Decoding", "MDCAT", "Easy", "A=3, B=4, C=5... DOG = ?", ["32", "33", "34", "35"], 1, "Sum of (position + 2) → 33."],
  [374, "Coding & Decoding", "FAST ET", "Medium", "If '789' is 'good bad ugly', '912' is 'ugly beautiful nice', what is 'ugly'?", ["7", "8", "9", "1"], 2, "Common digit for ugly is 9."],
  [375, "Coding & Decoding", "NTC", "Hard", "If 'eat fresh fruit' is '3 4 5', 'fruit is sweet' is '5 6 7', what is 'fruit'?", ["3", "4", "5", "6"], 2, "Common digit for fruit is 5."],
  [376, "Coding & Decoding", "ISSB", "Easy", "If PLANT is QMBOU, SEED is?", ["TFFE", "TFFD", "TFEF", "TGEE"], 0, "Shift +1 each letter → TFFE."],
  [377, "Coding & Decoding", "NET", "Medium", "If CLOCK is AJMIA, WATCH is?", ["UYRAF", "UYSAE", "UYRAF", "UYSAF"], 0, "Shift -2 each letter → UYRAF."],
  [378, "Coding & Decoding", "MDCAT", "Hard", "If KING is PRMT, QUEEN is?", ["JFVVM", "JFVVN", "KFVVM", "KFVVN"], 0, "Opposite alphabet letters → JFVVM."],
  [379, "Coding & Decoding", "FAST ET", "Easy", "Code C as 7, A as 8, R as 9. CAR is?", ["789", "897", "978", "798"], 0, "Direct position substitution → 789."],
  [380, "Coding & Decoding", "NTC", "Medium", "Code I=3, J=6, K=9. L=?", ["10", "11", "12", "13"], 2, "Multiples of 3: L = 12."],
  [381, "Coding & Decoding", "ISSB", "Hard", "Code BIN as 2914, TIN as?", ["20914", "20915", "20916", "20917"], 0, "T(20) I(9) N(14) → 20914."],
  [382, "Coding & Decoding", "NET", "Easy", "Code PEN as !@#, MEN as $@#. P is?", ["!", "@", "#", "$"], 0, "First symbol is !."],
  [383, "Coding & Decoding", "MDCAT", "Medium", "Code STONE as ~!@#$, TONES is?", ["!@#$~", "!#@$~", "!@#~$", "!@~$#"], 0, "Symbol rearrangement → !@#$~."],
  [384, "Coding & Decoding", "FAST ET", "Hard", "If S=19, SO=34, then SOME=?", ["51", "52", "53", "54"], 1, "Sum of positions: 19+15+13+5 = 52."],
  [385, "Coding & Decoding", "NTC", "Easy", "Code FAST as GBTU, SLOW as?", ["TMPX", "TMOX", "TMPY", "TMOY"], 0, "Shift +1 each letter → TMPX."],
  [386, "Coding & Decoding", "ISSB", "Medium", "If WATER is 23-1-20-5-18, ICE is?", ["9-3-5", "9-3-6", "9-4-5", "9-4-6"], 0, "Alphabet positions → 9-3-5."],
  [387, "Coding & Decoding", "NET", "Hard", "If RED = 3, BLUE = 4, YELLOW = ?", ["4", "5", "6", "7"], 2, "Number of letters in YELLOW = 6."],
  [388, "Coding & Decoding", "MDCAT", "Easy", "If P=15, Q=16, R=17. S=?", ["17", "18", "19", "20"], 1, "S = 18."],
  [389, "Direction Sense Tests", "FAST ET", "Easy", "Walk 6km East, turn North 8km. Distance?", ["8km", "9km", "10km", "14km"], 2, "d = √(6² + 8²) = 10 km."],
  [390, "Direction Sense Tests", "NTC", "Medium", "Face East, turn 180°. Facing?", ["North", "South", "West", "East"], 2, "180° rotation → West."],
  [391, "Direction Sense Tests", "ISSB", "Hard", "Face East, turn 45° CCW, then 180°. Facing?", ["SW", "NW", "SE", "NE"], 0, "45° CCW - 180° = 135° CCW from East → South-West."],
  [392, "Direction Sense Tests", "NET", "Easy", "P is East of Q. R is North of Q. P to R?", ["SE", "SW", "NE", "NW"], 0, "P relative to R is South-East."],
  [393, "Direction Sense Tests", "MDCAT", "Medium", "Walk 15km E, turn R 10km, turn R 15km. Distance?", ["10km", "15km", "20km", "25km"], 0, "Displacement is 10km South."],
  [394, "Direction Sense Tests", "FAST ET", "Hard", "Morning shadow falls to the right. Facing?", ["North", "South", "East", "West"], 1, "Sun in East; right shadow means facing South."],
  [395, "Direction Sense Tests", "NTC", "Easy", "Move 8m E, 8m N, 8m W. Where from start?", ["8m E", "8m W", "8m N", "8m S"], 2, "8 meters North of start."],
  [396, "Direction Sense Tests", "ISSB", "Medium", "Turn 90° CW, then 180° CCW. Facing?", ["Right", "Left", "Same", "Opposite"], 1, "Net 90° CCW turn (Left)."],
  [397, "Direction Sense Tests", "NET", "Hard", "If East becomes SE, what does North become?", ["NE", "NW", "SW", "SE"], 0, "45° CW shift: North becomes North-East."],
  [398, "Direction Sense Tests", "MDCAT", "Easy", "Clock 9:00. Minute hand points N. Hour hand points?", ["W", "E", "N", "S"], 0, "Hour hand at 9 points West."],
  [399, "Direction Sense Tests", "FAST ET", "Medium", "Walk 1km E, 2km N, 1km W. Distance from start?", ["1km", "2km", "3km", "4km"], 1, "Displacement is 2km North."],
  [400, "Direction Sense Tests", "NTC", "Hard", "P is 6m E of Q. R is 8m N of Q. Distance P to R?", ["8m", "10m", "12m", "14m"], 1, "d = √(6² + 8²) = 10 m."],

  // ─── BATCH 9: Q401 to Q450 ───
  [401, "Direction Sense Tests", "ISSB", "Easy", "Moving E, take 2 left turns. Facing?", ["W", "E", "N", "S"], 0, "180° rotation → West."],
  [402, "Direction Sense Tests", "NET", "Medium", "In morning, P & Q face each other. P's shadow is on Q. P faces?", ["E", "W", "N", "S"], 4, "Option E / West."],
  [403, "Direction Sense Tests", "MDCAT", "Hard", "Walk 3km E, 3km N, 3km W, 3km S. Final position?", ["3km E", "3km N", "3km S", "Start point"], 3, "Returns to starting point."],
  [404, "Direction Sense Tests", "FAST ET", "Easy", "Walk 15m E, turn 180, walk 15m. Where from start?", ["Start", "15m E", "15m W", "30m E"], 0, "Returns to starting point."],
  [405, "Direction Sense Tests", "NTC", "Medium", "Face N, turn 90° CW, then 135° CCW. Facing?", ["NW", "NE", "SW", "SE"], 0, "90° CW - 135° CCW = 45° CCW from North → North-West."],
  [406, "Direction Sense Tests", "ISSB", "Hard", "From P, Q is E. From Q, R is S. From P, R is?", ["SE", "SW", "NE", "NW"], 0, "Relative direction is South-East."],
  [407, "Direction Sense Tests", "NET", "Easy", "Start E, take L, then L, then R. Facing?", ["N", "S", "E", "W"], 0, "East → Left (N) → Left (W) → Right (N)."],
  [408, "Direction Sense Tests", "MDCAT", "Medium", "Clock 12:30. Minute hand points S. Hour hand points?", ["N", "S", "E", "W"], 0, "Hour hand at 12 points North."],
  [409, "Direction Sense Tests", "FAST ET", "Hard", "Walk 3km E, 3km SE. General direction from start?", ["SE", "SW", "NE", "NW"], 0, "General direction is South-East."],
  [410, "Direction Sense Tests", "NTC", "Easy", "Map: Top is W, Right is N. Bottom is?", ["E", "W", "S", "N"], 0, "Opposite of West is East."],
  [411, "Direction Sense Tests", "ISSB", "Medium", "I face E. Turn 90° CCW, walk 3m, turn 90° CCW, walk 4m. Distance?", ["5m", "7m", "1m", "6m"], 0, "d = √(3² + 4²) = 5 m."],
  [412, "Direction Sense Tests", "NET", "Hard", "Go 8km E, then 8km S, then 8km SE. Final direction?", ["SE", "SW", "NE", "NW"], 0, "Final direction is South-East."],
  [413, "Direction Sense Tests", "MDCAT", "Easy", "Walk 3km E, 4km S, 5km W, 6km N. General direction?", ["NW", "NE", "SW", "SE"], 0, "Displacement (-2 West, +2 North) → North-West."],
  [414, "Blood Relations", "FAST ET", "Easy", "P is Q's father. R is Q's sister. P to R?", ["Father", "Uncle", "Brother", "Grandfather"], 0, "P is the father of R."],
  [415, "Blood Relations", "NTC", "Medium", "Pointing to a boy, Sara says: 'He is the son of my grandfather's only son.' Boy to Sara?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Boy is her brother."],
  [416, "Blood Relations", "ISSB", "Hard", "AB means A is husband of B. A#B means A is wife of B. What is MN#O?", ["Invalid", "M is brother of O", "M is father of O", "M is son of O"], 0, "Invalid relationship structure."],
  [417, "Blood Relations", "NET", "Easy", "P's sister is daughter of Q. Q's sister is R. P to R?", ["Nephew/Niece", "Grandchild", "Son/Daughter", "Brother/Sister"], 0, "P is nephew/niece of R."],
  [418, "Blood Relations", "MDCAT", "Medium", "P is Q's father. R is P's father. S is R's father. T is S's father. Q to R?", ["Grandchild", "Child", "Great-grandchild", "Nephew"], 0, "Q is the grandchild of R."],
  [419, "Blood Relations", "FAST ET", "Hard", "Pointing to a boy, a girl says: 'His sister is my mother's only daughter.' Boy to girl?", ["Brother", "Husband", "Uncle", "Father"], 0, "Boy is her brother."],
  [420, "Blood Relations", "NTC", "Easy", "P is grandfather of Q. Q is son of R. R is husband of S. P to R?", ["Father", "Father-in-law", "Uncle", "Brother"], 0, "P is the father of R."],
  [421, "Blood Relations", "ISSB", "Medium", "If X&Y means X is brother of Y; X*Y means X is father of Y. Which means M is uncle of N?", ["M&O*N", "M*O&N", "M%O*N", "M*O%N"], 0, "M is brother of O, O is father of N → M&O*N."],
  [422, "Blood Relations", "NET", "Hard", "'He is the husband of my mother's only daughter.' Relation to speaker (male)?", ["Brother-in-law", "Brother", "Uncle", "Cousin"], 0, "He is brother-in-law."],
  [423, "Blood Relations", "MDCAT", "Easy", "C's brother's father's brother's son is?", ["Cousin", "Brother", "Uncle", "Nephew"], 0, "He is C's cousin."],
  [424, "Blood Relations", "FAST ET", "Medium", "P is Q's brother. R is Q's mother. S is R's father. T is S's mother. How is P related to T?", ["Great-grandson", "Grandson", "Son", "Brother"], 0, "P is the great-grandson of T."],
  [425, "Blood Relations", "NTC", "Hard", "Pointing to a photograph, a woman says, 'This man's son's sister is my mother-in-law.' Woman's husband to man?", ["Grandson", "Son", "Nephew", "Son-in-law"], 0, "He is the grandson of the man."],
  [426, "Blood Relations", "ISSB", "Easy", "A is B's brother, C is A's mother, D is C's father, E is B's son. How is D related to A?", ["Grandfather", "Great-grandfather", "Father", "Uncle"], 0, "D is the grandfather of A."],
  [427, "Blood Relations", "NET", "Medium", "If X+Y means X is father of Y; X-Y means X is wife of Y. How is A related to B in A+CB?", ["Father", "Uncle", "Brother", "Grandfather"], 0, "A is father of B."],
  [428, "Blood Relations", "MDCAT", "Hard", "Read: A+B=father, A-B=mother, AB=brother. P/Q+RS. P to S?", ["Aunt", "Mother", "Grandmother", "Sister"], 0, "P is aunt of S."],
  [429, "Blood Relations", "FAST ET", "Easy", "Introducing a man, a woman says, 'He is the brother of the daughter of the wife of my husband.' Man to woman?", ["Son", "Brother", "Nephew", "Uncle"], 0, "Man is her son."],
  [430, "Blood Relations", "NTC", "Medium", "P's brother Q is son of R's sister S. How is Q related to R?", ["Nephew", "Son", "Brother", "Uncle"], 0, "Q is the nephew of R."],
  [431, "Blood Relations", "ISSB", "Hard", "A, B, C, D, E, F are family. 2 married couples. B is engineer and father of E. F is grandfather of C and doctor. D is grandmother of E and housewife. Total females?", ["2", "3", "4", "Cannot be determined"], 1, "There are 3 females."],
  [432, "Blood Relations", "NET", "Easy", "Girl points to boy: 'He is the brother of my mother's father's only granddaughter.' Relation?", ["Brother", "Cousin", "Uncle", "Nephew"], 0, "Boy is her brother."],
  [433, "Blood Relations", "MDCAT", "Medium", "P is son of Q. Q is son of R. R is husband of S. T is mother of P. S is related to T as?", ["Grandmother", "Mother", "Mother-in-law", "Aunt"], 2, "S is mother-in-law of T."],
  [434, "Blood Relations", "FAST ET", "Hard", "A+B=father, A-B=mother, AB=brother, A/B=sister. MN$O-P. M to P?", ["Uncle", "Father", "Grandfather", "Brother"], 0, "M is uncle of P."],
  [435, "Blood Relations", "NTC", "Easy", "My brother's only sister's husband's only daughter's brother is my?", ["Nephew", "Son", "Cousin", "Brother"], 0, "He is my nephew."],
  [436, "Blood Relations", "ISSB", "Medium", "P is Q's grandfather. Q is R's brother. R is S's son. S is T's wife. P to T?", ["Father-in-law", "Father", "Uncle", "Brother"], 0, "P is father-in-law of T."],
  [437, "Blood Relations", "NET", "Hard", "Pointing to a boy, a girl says: 'His sister's mother's brother's only daughter is my sister.' Boy to girl?", ["Cousin", "Brother", "Uncle", "Nephew"], 0, "They are cousins."],
  [438, "Blood Relations", "MDCAT", "Easy", "P is Q's mother's sister's only brother's son. P to Q?", ["Cousin", "Brother", "Nephew", "Uncle"], 0, "P is cousin of Q."],
  [439, "Number & Letter Series", "FAST ET", "Easy", "Next in series: 1, 3, 5, 7, ?", ["8", "9", "10", "11"], 1, "Odd numbers sequence: 7 + 2 = 9."],
  [440, "Number & Letter Series", "NTC", "Easy", "Missing term: 2, 5, 10, 17, ?", ["24", "25", "26", "27"], 2, "Pattern n² + 1: 5² + 1 = 26."],
  [441, "Number & Letter Series", "ISSB", "Medium", "Find the odd one out: 4, 16, 25, 36, 42", ["4", "16", "36", "42"], 3, "42 is not a perfect square."],
  [442, "Number & Letter Series", "NET", "Hard", "Next in series: 3, 4, 12, 39, 103, ?", ["228", "250", "213", "312"], 0, "Pattern +1³, +2³, +3³, +4³, +5³: 103 + 125 = 228."],
  [443, "Number & Letter Series", "MDCAT", "Easy", "Next in series: A, C, E, G, ?", ["H", "I", "J", "K"], 1, "Skip 1 letter (+2 positions): G (+2) = I."],
  [444, "Number & Letter Series", "FAST ET", "Medium", "Next in series: A, E, I, M, ?", ["O", "P", "Q", "R"], 2, "Step +4 positions: M (+4) = Q."],
  [445, "Number & Letter Series", "NTC", "Hard", "Next in series: ZA, YB, XC, WD, ?", ["VE", "UE", "VF", "UF"], 0, "Reverse & forward pairs → VE."],
  [446, "Number & Letter Series", "ISSB", "Easy", "Complete: FAG, GAF, HAI, IAH, ___", ["JAK", "HAL", "HAK", "JAI"], 0, "Sequence pattern → JAK."],
  [447, "Number & Letter Series", "NET", "Medium", "Complete: P5QR, P4QS, P3QT, ___, P1QV", ["PQW", "PQV2", "P2QU", "PQ3U"], 2, "Number decreases, last letter steps → P2QU."],
  [448, "Number & Letter Series", "MDCAT", "Hard", "Missing term: 3F, 6G, 11I, 18L, ?", ["21O", "25N", "27P", "27O"], 2, "Pattern num +9, letter +4 → 27P."],
  [449, "Number & Letter Series", "FAST ET", "Easy", "Next in series: 36, 34, 30, 28, 24, ?", ["20", "22", "23", "26"], 1, "Alternating -2, -4, -2, -4, -2: 24 - 2 = 22."],
  [450, "Number & Letter Series", "NTC", "Medium", "Next in series: 15, 14, 13, 12", ["15", "14", "13", "12"], 0, "Sequence step → 15."],

  // ─── BATCH 10: Q451 to Q500 ───
  [451, "Number & Letter Series", "ISSB", "Hard", "What comes next: 71, 55, 46, 42, ?", ["39", "40", "41", "42"], 2, "Differences are -16 (-4²), -9 (-3²), -4 (-2²), -1 (-1²): 42 - 1 = 41."],
  [452, "Number & Letter Series", "NET", "Easy", "Series: B, F, J, N, R, V, ?", ["X", "Z", "Y", "W"], 1, "Step of +4 positions: V (+4) = Z."],
  [453, "Number & Letter Series", "MDCAT", "Medium", "Series: X, U, R, O, L, I, ?", ["F", "E", "G", "D"], 0, "Step back by -3 positions: I (-3) = F."],
  [454, "Number & Letter Series", "FAST ET", "Hard", "Series: AB, DEF, HIJK, ?", ["LMNO", "MNOPQ", "NOPQR", "OPQRS"], 1, "Length increases by 1 each step (2,3,4,5 letters) → MNOPQ."],
  [455, "Number & Letter Series", "NTC", "Easy", "3, 6, 12, 24, 48, 96, ?", ["192", "144", "288", "150"], 0, "Doubling sequence: 96 × 2 = 192."],
  [456, "Number & Letter Series", "ISSB", "Medium", "20, 40, 80, 160, 320, ?", ["640", "600", "500", "700"], 0, "Doubling sequence: 320 × 2 = 640."],
  [457, "Number & Letter Series", "NET", "Hard", "2, 3, 10, 39, 172, ?", ["885", "880", "875", "890"], 0, "Pattern ×1+1², ×2+2², ×3+3², ×4+4², ×5+5²: 172×5 + 25 = 885."],
  [458, "Number & Letter Series", "MDCAT", "Easy", "2, 5, 11, 23, 47, ?", ["95", "96", "97", "98"], 0, "Pattern ×2 + 1: 47 × 2 + 1 = 95."],
  [459, "Number & Letter Series", "FAST ET", "Medium", "8, 17, 35, 71, 143, ?", ["286", "287", "288", "289"], 1, "Pattern ×2 + 1: 143 × 2 + 1 = 287."],
  [460, "Number & Letter Series", "NTC", "Hard", "5, 16, 49, 148, 445, ?", ["1334", "1335", "1336", "1337"], 2, "Pattern ×3 + 1: 445 × 3 + 1 = 1336."],
  [461, "Number & Letter Series", "ISSB", "Easy", "A, Z, C, X, E, ?", ["V", "U", "W", "Y"], 0, "Forward odd positions (A,C,E) / Reverse even (Z,X,V) → V."],
  [462, "Coding & Decoding", "NET", "Easy", "If RED is 27, BLUE is?", ["40", "42", "45", "48"], 0, "Sum of positions + count → 40."],
  [463, "Coding & Decoding", "MDCAT", "Medium", "If PEN is 35, INK is?", ["30", "32", "34", "36"], 2, "Sum of letter positions → 34."],
  [464, "Coding & Decoding", "FAST ET", "Hard", "If PLAN = NHYJ, STAR = ?", ["QPYN", "ROXM", "RPYM", "SPYM"], 0, "Shift code → QPYN."],
  [465, "Coding & Decoding", "NTC", "Easy", "If HE is 13, SHE is?", ["30", "31", "32", "33"], 2, "Sum of positions S(19)+H(8)+E(5) = 32."],
  [466, "Coding & Decoding", "ISSB", "Medium", "If MAN is 28, WOMAN is?", ["64", "65", "66", "67"], 2, "Sum of positions → 66."],
  [467, "Coding & Decoding", "NET", "Hard", "If ROSE is 6821, CHAIR is 73456, SEARCH is?", ["214673", "214674", "214675", "214676"], 0, "Direct letter substitution → 214673."],
  [468, "Coding & Decoding", "MDCAT", "Easy", "If BOOK = CPPL, DOOR = ?", ["DPPS", "EPPS", "EQPS", "DPPR"], 1, "Shift +1 each letter → EPPS."],
  [469, "Coding & Decoding", "FAST ET", "Medium", "If APPLE = BQQMF, ORANGE = ?", ["PQBOHF", "PSBOHE", "PSCOHF", "PQCOHE"], 0, "Shift +1 each letter → PQBOHF."],
  [470, "Coding & Decoding", "NTC", "Hard", "If 'water' is 'food', 'food' is 'tree', 'tree' is 'sky', what do we drink?", ["food", "tree", "sky", "water"], 0, "We drink water, and water is 'food'."],
  [471, "Coding & Decoding", "ISSB", "Easy", "A=2, B=4, C=6... APPLE = ?", ["100", "102", "104", "106"], 0, "2 × sum of positions: 2 × (1+16+16+12+5) = 100."],
  [472, "Coding & Decoding", "NET", "Medium", "If '456' is 'cold winter day', '678' is 'hot summer day', what is 'day'?", ["4", "5", "6", "7"], 2, "Common digit is 6."],
  [473, "Coding & Decoding", "MDCAT", "Hard", "If 'good and bad' is '7 2 5', 'bad and ugly' is '5 2 9', what is 'and'?", ["7", "2", "5", "9"], 1, "Common digit for 'and' is 2."],
  [474, "Coding & Decoding", "FAST ET", "Easy", "If STONE is TUPPF, BRICK is?", ["CSJDL", "CSJDM", "CTJDL", "CTJDM"], 0, "Shift +1 each letter → CSJDL."],
  [475, "Coding & Decoding", "NTC", "Medium", "If BOARD is ZMYPB, PAPER is?", ["NYNCP", "NYOCP", "NYNDP", "NYODP"], 0, "Letter substitution → NYNCP."],
  [476, "Coding & Decoding", "ISSB", "Hard", "If READ is IVZW, WRITE is?", ["DIRT", "DIRV", "DHRV", "DHIV"], 1, "Shift code → DIRV."],
  [477, "Coding & Decoding", "NET", "Easy", "Code B as 4, A as 5, T as 6. BAT is?", ["456", "564", "645", "465"], 0, "Substitution → 456."],
  [478, "Coding & Decoding", "MDCAT", "Medium", "Code E=2, F=4, G=6. H=?", ["7", "8", "9", "10"], 1, "Multiples of 2: H = 4 × 2 = 8."],
  [479, "Coding & Decoding", "FAST ET", "Hard", "Code RAT as 18120, MAT as?", ["13120", "13121", "13122", "13123"], 0, "M(13) A(1) T(20) → 13120."],
  [480, "Coding & Decoding", "NTC", "Easy", "Code CAR as %^&, BAR as *^&. C is?", ["%", "^", "&", "*"], 0, "Symbol is %."],
  [481, "Coding & Decoding", "ISSB", "Medium", "Code EARTH as &*@#%, HEART is?", ["%*@#&", "%*&#@", "%#*@&", "%*@&#"], 3, "Symbol rearrangement → %*@&#."],
  [482, "Coding & Decoding", "NET", "Hard", "If H=8, HE=13, then HERE=?", ["35", "36", "37", "38"], 1, "Sum of positions = 36."],
  [483, "Coding & Decoding", "MDCAT", "Easy", "Code COOL as DPPM, WARM as?", ["XBSN", "XCSN", "XBSO", "XCSO"], 0, "Shift +1 each letter → XBSN."],
  [484, "Coding & Decoding", "FAST ET", "Medium", "If COFFEE is 3-15-6-6-5-5, MILK is?", ["13-9-12-11", "13-9-12-12", "13-10-12-11", "13-10-12-12"], 0, "Alphabet positions M(13)-I(9)-L(12)-K(11)."],
  [485, "Coding & Decoding", "NTC", "Hard", "If ONE = 3, TWO = 3, THREE = ?", ["3", "4", "5", "6"], 2, "Letter count of THREE = 5."],
  [486, "Coding & Decoding", "ISSB", "Easy", "If Z=25, Y=24, X=23. W=?", ["20", "21", "22", "23"], 2, "Reverse position of W = 22."],
  [487, "Direction Sense Tests", "NET", "Easy", "Walk 3km South, turn West 4km. Distance?", ["5km", "6km", "7km", "8km"], 0, "d = √(3² + 4²) = 5 km."],
  [488, "Direction Sense Tests", "MDCAT", "Medium", "Face South, turn 90° CCW. Facing?", ["East", "West", "North", "South-East"], 0, "90° CCW from South is East."],
  [489, "Direction Sense Tests", "FAST ET", "Hard", "Face South, turn 135° CW. Facing?", ["NW", "NE", "SW", "SE"], 0, "135° CW from South is North-West."],
  [490, "Direction Sense Tests", "NTC", "Easy", "X is South of Y. Z is West of Y. X to Z?", ["SE", "SW", "NE", "NW"], 0, "X relative to Z is South-East."],
  [491, "Direction Sense Tests", "ISSB", "Medium", "Walk 20km S, turn L 10km, turn L 20km. Distance?", ["10km", "20km", "30km", "40km"], 0, "Distance from start is 10km East."],
  [492, "Direction Sense Tests", "NET", "Hard", "Start moving towards Sun in evening, turn right. Facing?", ["North", "South", "East", "West"], 0, "Sun in evening is West; right turn leads North."],
  [493, "Direction Sense Tests", "MDCAT", "Easy", "Move 5m S, 5m W, 5m N. Where from start?", ["5m E", "5m W", "5m N", "5m S"], 1, "5 meters West of start."],
  [494, "Direction Sense Tests", "FAST ET", "Medium", "Turn 180° CW, then 180° CCW. Facing?", ["Same", "Opposite", "Right", "Left"], 0, "Net rotation is 0° → Same direction."],
  [495, "Direction Sense Tests", "NTC", "Hard", "If South becomes SW, what does West become?", ["NW", "NE", "SE", "SW"], 0, "45° CCW shift: West becomes North-West."],
  [496, "Direction Sense Tests", "ISSB", "Easy", "Clock shows 6:00. Hour hand points S. Minute hand points?", ["N", "S", "E", "W"], 0, "Minute hand at 12 points North."],
  [497, "Direction Sense Tests", "NET", "Medium", "Walk 4km S, 5km W, 4km N. Distance from start?", ["3km", "4km", "5km", "6km"], 2, "Displacement is 5km West."],
  [498, "Direction Sense Tests", "MDCAT", "Hard", "X is 3m S of Y. Z is 4m W of Y. Distance X to Z?", ["3m", "4m", "5m", "7m"], 2, "d = √(3² + 4²) = 5 m."],
  [499, "Direction Sense Tests", "FAST ET", "Easy", "Moving S, take 3 right turns. Facing?", ["E", "W", "N", "S"], 0, "3 right turns (270° CW) = 1 left turn → East."],
  [500, "Direction Sense Tests", "NTC", "Medium", "In evening, X & Y face each other. X's shadow is to his left. Y faces?", ["N", "S", "E", "W"], 1, "X faces North, so Y faces South."]
];

rawIQ.forEach(([id, topic, testTag, difficulty, q, opts, ans, exp]) => {
    addQ(id, topic, testTag, difficulty, q, opts, ans, exp);
});

console.log(`Generated ${mcqs.length} IQ MCQs!`);
const targetPath = path.join(__dirname, 'public/data/mcqs/iq.json');
fs.writeFileSync(targetPath, JSON.stringify(mcqs, null, 2));
console.log(`Successfully written 500 IQ MCQs to ${targetPath}`);
